"""HTTP-layer tests for the commentary route (KCH-62 / AA-25).

Same fake-connection approach as tests/api/test_dashboard_routes.py: the SQL
wrapper itself is exercised against real Postgres in
tests/db/test_audit_commentary_live.py.
"""

from __future__ import annotations

import json
from datetime import date

import pytest
from fastapi.testclient import TestClient

from app.auth import get_current_user_id
from app.main import app
from app.routes import commentary as commentary_module

USER_ID = "00000000-0000-0000-0000-000000000042"

client = TestClient(app)


class FakeConnection:
    def __init__(self, *, row):
        self.row = row

    async def fetchrow(self, query, *args):
        return self.row


@pytest.fixture(autouse=True)
def _auth_override():
    app.dependency_overrides[get_current_user_id] = lambda: USER_ID
    yield
    app.dependency_overrides.pop(get_current_user_id, None)


@pytest.fixture(autouse=True)
def _clear_conn_override():
    yield
    app.dependency_overrides.pop(commentary_module._conn, None)


def _override_conn(*, row):
    fake = FakeConnection(row=row)

    async def _fake_conn():
        yield fake

    app.dependency_overrides[commentary_module._conn] = _fake_conn
    return fake


def _commentary_row(**overrides) -> dict:
    row = {
        "snapshot_date": date(2026, 7, 31),
        "observations": json.dumps(["Tech is 48% of your holdings."]),
        "disclosure": "Generated by AI. Not financial advice.",
        "model_backend": "groq",
        "run_id": "some-run-id",
        "created_at": None,
    }
    row.update(overrides)
    return row


def test_get_commentary_returns_observations_and_disclosure():
    _override_conn(row=_commentary_row())

    response = client.get("/api/commentary")

    assert response.status_code == 200
    body = response.json()
    assert body["as_of"] == "2026-07-31"
    assert body["observations"] == ["Tech is 48% of your holdings."]
    assert body["disclosure"] == "Generated by AI. Not financial advice."
    assert body["model_backend"] == "groq"


def test_get_commentary_decodes_observations_already_a_list():
    _override_conn(row=_commentary_row(observations=["Already decoded."]))

    response = client.get("/api/commentary")

    assert response.status_code == 200
    assert response.json()["observations"] == ["Already decoded."]


def test_get_commentary_404s_when_none_generated_yet():
    _override_conn(row=None)

    response = client.get("/api/commentary")

    assert response.status_code == 404


def test_get_commentary_requires_auth():
    app.dependency_overrides.pop(get_current_user_id, None)

    response = client.get("/api/commentary")

    assert response.status_code == 401
