"""Gold facts -> plain-language observations, pure (KCH-62 / AA-25).

Same domain/IO split as `app.domain.dashboard`/`app.domain.diversification_flags`:
this module never touches the network or the DB. `worker.commentary` is the
only caller of the LLM (`docs/vault/30-architecture/LLM-Strategy.md` role 3,
"Audit commentary"); everything here is deterministic input-shaping for that
call and deterministic guardrail-checking of its output.

`GoldFactsSnapshot` carries only figures the dashboard (AA-22) already shows
the user — snapshot totals, term buckets, diversification-by-institution —
never raw statement text or an account number, so unlike
`worker.masking.mask_statement_text` there is nothing here to mask before
the LLM sees it: aggregate CAD totals and institution labels are exactly
what `app.routes.dashboard` already returns to the frontend unmasked.

`docs/vault/10-mental-models/LLM-as-Parser-not-Oracle.md`: the model "never
invents numbers, never does arithmetic that matters"; `render_facts_for_prompt`
does every percentage/rounding calculation itself so the model is only ever
asked to describe numbers already computed, never to compute or restate them
differently. `filter_advice_shaped` is the compliance backstop for
mvp.md's AA-25 "never advice-shaped" requirement — the system prompt
(`worker.commentary`) asks the model not to give advice, but a prompt is not
a guarantee, so every observation is checked deterministically before it
ever reaches a user, same "observations, never directives" posture
`app.domain.diversification_flags` already established for AA-24.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from typing import Any

ZERO = Decimal("0")
HUNDRED = Decimal("100")

DISCLOSURE_TEXT = (
    "These observations were generated by an AI model from your account data. "
    "They describe patterns in your numbers, not financial advice — always "
    "verify important decisions with a qualified professional."
)

MIN_OBSERVATIONS = 1
MAX_OBSERVATIONS = 6


@dataclass(frozen=True)
class DiversificationSlice:
    label: str
    amount_cad: Decimal


@dataclass(frozen=True)
class GoldFactsSnapshot:
    """The exact figures `app.routes.dashboard.get_dashboard` already
    returns for this user's latest snapshot — nothing derived here that the
    user can't already see on the dashboard itself."""

    as_of: date
    total_assets_cad: Decimal
    total_liabilities_cad: Decimal
    net_worth_cad: Decimal
    term_buckets: dict[str, Decimal]
    diversification_by_institution: list[DiversificationSlice]


def build_gold_facts_snapshot(
    *,
    as_of: date,
    total_assets_cad: Decimal,
    total_liabilities_cad: Decimal,
    net_worth_cad: Decimal,
    term_buckets: dict[str, Decimal],
    diversification_by_institution: list[DiversificationSlice],
) -> GoldFactsSnapshot:
    return GoldFactsSnapshot(
        as_of=as_of,
        total_assets_cad=total_assets_cad,
        total_liabilities_cad=total_liabilities_cad,
        net_worth_cad=net_worth_cad,
        term_buckets=dict(term_buckets),
        diversification_by_institution=list(diversification_by_institution),
    )


def _pct(amount: Decimal, total: Decimal) -> str:
    if total <= ZERO:
        return "n/a"
    return f"{(amount / total * HUNDRED):.1f}%"


def render_facts_for_prompt(facts: GoldFactsSnapshot) -> str:
    """Deterministic plain-text rendering of `facts` for the LLM's user
    message — the only thing `worker.commentary.request_commentary` sends.

    Every number is pre-formatted (dollar amounts, percentages) so the model
    is describing, not computing — `compute_gold_totals`/`reconcile_assets_to_cad`
    (AA-18/AA-22) already did the arithmetic that matters.
    """
    lines = [
        f"As of {facts.as_of.isoformat()}:",
        f"Total assets: ${facts.total_assets_cad:,.2f} CAD",
        f"Total liabilities: ${facts.total_liabilities_cad:,.2f} CAD",
        f"Net worth: ${facts.net_worth_cad:,.2f} CAD",
    ]

    if facts.term_buckets:
        lines.append("")
        lines.append("Term buckets:")
        for bucket, amount in sorted(facts.term_buckets.items()):
            lines.append(
                f"- {bucket}: ${amount:,.2f} CAD "
                f"({_pct(amount, facts.total_assets_cad)} of total assets)"
            )

    if facts.diversification_by_institution:
        lines.append("")
        lines.append("Diversification by institution:")
        for slice_ in facts.diversification_by_institution:
            lines.append(
                f"- {slice_.label}: ${slice_.amount_cad:,.2f} CAD "
                f"({_pct(slice_.amount_cad, facts.total_assets_cad)} of total assets)"
            )

    return "\n".join(lines)


# Word-boundary patterns for imperative/advisory language: directives
# ("you should", "consider selling"), first-person recommendation framing,
# and the specific verbs a buy/sell/rebalance suggestion would use. Deliberately
# broad — a false-positive-dropped observation (fewer cards) is the safe
# failure mode here, an advice-shaped sentence reaching the user is not.
_ADVICE_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(pattern, re.IGNORECASE)
    for pattern in (
        r"\byou should\b",
        r"\byou (ought|need) to\b",
        r"\b(we|i) recommend\b",
        r"\bmy (advice|recommendation)\b",
        r"\bconsider (selling|buying|investing|rebalancing|moving|switching)\b",
        r"\bit('|’)s time to\b",
        r"\b(sell|buy|invest in|rebalance|diversify into|switch to|move (your|some) "
        r"(money|funds|assets))\b",
    )
)


def is_advice_shaped(observation: str) -> bool:
    return any(pattern.search(observation) for pattern in _ADVICE_PATTERNS)


def filter_advice_shaped(observations: list[str]) -> list[str]:
    """Drop any observation matching `_ADVICE_PATTERNS` and any blank/whitespace
    entry. Order-preserving; callers decide what an empty result means."""
    return [obs.strip() for obs in observations if obs.strip() and not is_advice_shaped(obs)]


def decode_observations(raw: str | list[Any]) -> list[str]:
    """`audit_commentary.observations` round-trip, same jsonb-as-text
    convention `app.domain.staged_rows.decode_payload` documents — asyncpg
    hands back a jsonb column as a raw string unless a codec is registered,
    which this repo doesn't do."""
    return json.loads(raw) if isinstance(raw, str) else list(raw)


__all__ = [
    "DISCLOSURE_TEXT",
    "MIN_OBSERVATIONS",
    "MAX_OBSERVATIONS",
    "DiversificationSlice",
    "GoldFactsSnapshot",
    "build_gold_facts_snapshot",
    "render_facts_for_prompt",
    "is_advice_shaped",
    "filter_advice_shaped",
    "decode_observations",
]
