#!/usr/bin/env bash
# AssetAuditor overnight orchestrator
# Runs Claude Code headlessly against Linear backlog issues in dependency order,
# gates every branch through CodeRabbit before a PR is opened, mediates findings
# the implementing agent cannot service, and self-resumes after usage-limit windows.
#
# Nothing here ever merges. Human review on `development` is the only merge gate.
#
# Prereqs (all checked by preflight below):
#   - `claude` CLI logged in            (claude login)
#   - `gh` CLI authenticated             (gh auth login)
#   - `coderabbit` CLI authenticated     (coderabbit auth login)
#   - LINEAR_API_KEY + LINEAR_TEAM_KEY exported
#   - ops/queue.tsv generated by ops/seed_linear.py
#   - repo bootstrapped by ops/bootstrap_repo.sh (main + development + origin)
#
# Run inside tmux so it survives the laptop closing:
#   tmux new -s assetauditor
#   export LINEAR_API_KEY=lin_api_...  LINEAR_TEAM_KEY=ASA
#   ./ops/orchestrator.sh
#   (ctrl-b, d to detach; tmux attach -t assetauditor to check back in)

set -uo pipefail

OPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${REPO_DIR:-$(cd "$OPS_DIR/.." && pwd)}"
QUEUE_FILE="${QUEUE_FILE:-$OPS_DIR/queue.tsv}"
LOG_DIR="$OPS_DIR/logs"
STATE_FILE="$OPS_DIR/.completed_issues"
CONTRACTS_FILE="$OPS_DIR/.agent_contracts.md"
REPORT_FILE="$LOG_DIR/NIGHT_REPORT.md"

MAX_TURNS="${MAX_TURNS:-120}"
MAX_BUDGET_USD="${MAX_BUDGET_USD:-5.00}"
IMPL_MODEL="${IMPL_MODEL:-}"          # e.g. claude-sonnet-5 to stretch the budget
MEDIATOR_MODEL="${MEDIATOR_MODEL:-}"  # e.g. claude-opus-5 for judgement calls
LINEAR_API="https://api.linear.app/graphql"
LINEAR_TEAM_KEY="${LINEAR_TEAM_KEY:-}"

# ---- CodeRabbit gate policy -------------------------------------------------
# Blocking findings go back to the implementing agent CR_MAX_ROUNDS times. What
# survives goes to a mediator agent, which either fixes it, dismisses it with a
# written rationale, or escalates it as a Linear issue for the morning review.
CR_MAX_ROUNDS="${CR_MAX_ROUNDS:-2}"
CR_BLOCKING="${CR_BLOCKING:-critical|major|blocker|high}"
# 1 = refuse to push when CodeRabbit itself cannot run. Default 0: still open the
# PR (human review is the real gate) but flag it loudly in the PR body, the Linear
# comment and the night report, so an unreviewed branch can never look reviewed.
CR_REQUIRED="${CR_REQUIRED:-0}"

# Explicit allowlist. Anything not named here is denied outright — headless runs
# never prompt, so a missing entry silently cripples the agent rather than
# pausing for a human. Deliberately excludes rm, sudo, and curl-to-anywhere
# (the orchestrator owns all Linear/network calls, so agents cannot exfiltrate).
ALLOWED_TOOLS="Read,Write,Edit,Grep,Glob,\
Bash(git:*),Bash(gh:*),\
Bash(pytest:*),Bash(ruff:*),Bash(mypy:*),Bash(python3:*),Bash(python:*),\
Bash(pip:*),Bash(pip3:*),Bash(uv:*),Bash(npm:*),Bash(npx:*),Bash(node:*),\
Bash(psql:*),Bash(pg_dump:*),Bash(pg_restore:*),Bash(createdb:*),Bash(dropdb:*),\
Bash(pg_isready:*),Bash(docker:*),Bash(docker-compose:*),\
Bash(pip-audit:*),Bash(gitleaks:*),Bash(trivy:*),\
Bash(mkdir:*),Bash(ls:*),Bash(cat:*),Bash(cp:*),Bash(mv:*),Bash(touch:*),\
Bash(echo:*),Bash(head:*),Bash(tail:*),Bash(wc:*),Bash(diff:*),Bash(jq:*),\
Bash(sed:*),Bash(grep:*),Bash(find:*),Bash(sort:*),Bash(awk:*),Bash(make:*)"

mkdir -p "$LOG_DIR"
touch "$STATE_FILE" "$CONTRACTS_FILE"

# Rolling pointer to the previous issue's branch, for stacked-PR bases.
# SEED_LAST_BRANCH lets a fresh run continue an existing stack instead of
# re-basing on development and losing the unmerged work below it.
LAST_BRANCH="${SEED_LAST_BRANCH:-}"
LAST_ISSUE="${SEED_LAST_ISSUE:-upstream}"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
report() { echo "$*" >> "$REPORT_FILE"; }

# ---- Preflight ---------------------------------------------------------------
# Fail loudly at 22:00 rather than silently at 03:00 with eight broken branches.

preflight() {
  local fatal=0
  command -v claude     >/dev/null || { log "FATAL: claude CLI not found"; fatal=1; }
  command -v gh         >/dev/null || { log "FATAL: gh CLI not found"; fatal=1; }
  command -v jq         >/dev/null || { log "FATAL: jq not found"; fatal=1; }
  command -v coderabbit >/dev/null || { log "WARN: coderabbit CLI not found — gate will report 'unavailable'"; }

  gh auth status >/dev/null 2>&1 || { log "FATAL: gh not authenticated. Run: gh auth login"; fatal=1; }
  [ -n "$LINEAR_API_KEY" ]  || { log "FATAL: LINEAR_API_KEY not exported"; fatal=1; }
  [ -n "$LINEAR_TEAM_KEY" ] || { log "FATAL: LINEAR_TEAM_KEY not exported (e.g. ASA)"; fatal=1; }
  [ -f "$QUEUE_FILE" ]      || { log "FATAL: no queue at $QUEUE_FILE — run ops/seed_linear.py first"; fatal=1; }

  cd "$REPO_DIR" 2>/dev/null || { log "FATAL: REPO_DIR $REPO_DIR missing"; fatal=1; }
  git rev-parse --git-dir >/dev/null 2>&1 || { log "FATAL: $REPO_DIR is not a git repo — run ops/bootstrap_repo.sh"; fatal=1; }
  git rev-parse --verify origin/development >/dev/null 2>&1 \
    || { log "FATAL: origin/development missing — run ops/bootstrap_repo.sh"; fatal=1; }

  if command -v coderabbit >/dev/null && ! coderabbit auth status >/dev/null 2>&1; then
    log "WARN: coderabbit CLI is not authenticated (coderabbit auth login). Gate will flag every PR as unreviewed."
    [ "$CR_REQUIRED" = "1" ] && { log "FATAL: CR_REQUIRED=1 and CodeRabbit unusable"; fatal=1; }
  fi

  # Integration-test dependencies. Not fatal: agents are told what is unavailable
  # and must say so in their summary rather than faking a passing test.
  if ! pg_isready -q 2>/dev/null; then
    log "WARN: PostgreSQL not accepting connections. Attempting to start..."
    pg_ctl -D "$(brew --prefix 2>/dev/null)/var/postgresql@16" start >/dev/null 2>&1 \
      || brew services start postgresql@16 >/dev/null 2>&1 || true
    sleep 3
    pg_isready -q 2>/dev/null && log "PostgreSQL is up." || log "WARN: no local PostgreSQL — DB-backed issues will note unverified work."
  fi
  docker info >/dev/null 2>&1 || log "WARN: Docker daemon not running — container-dependent work will be written but not run."
  local node_major
  node_major=$(node -v 2>/dev/null | sed -E 's/^v([0-9]+).*/\1/')
  [ -n "$node_major" ] && [ "$node_major" -lt 20 ] \
    && log "WARN: node $(node -v) — modern Vite needs node 20+. Frontend issues may need a node upgrade."

  [ "$fatal" -eq 1 ] && { log "Preflight failed. Nothing was run."; exit 1; }
  log "Preflight OK."
}

# ---- Linear GraphQL helpers -------------------------------------------------

linear_query() {
  local query="$1"
  curl -s -X POST "$LINEAR_API" \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg q "$query" '{query: $q}')"
}

# Resolve human-readable identifier (e.g. ASA-9) to Linear's internal UUID + state
resolve_issue() {
  local identifier="$1"
  linear_query "{ issues(filter: { number: { eq: ${identifier##*-} }, team: { key: { eq: \"${identifier%-*}\" } } }) { nodes { id identifier title description state { id name } } } }" \
    | jq -r '.data.issues.nodes[0]'
}

team_uuid() {
  linear_query "{ teams(filter: { key: { eq: \"$LINEAR_TEAM_KEY\" } }) { nodes { id } } }" \
    | jq -r '.data.teams.nodes[0].id // empty'
}

set_issue_state() {
  local issue_uuid="$1" state_name="$2"
  local tid state_id
  tid=$(team_uuid); [ -z "$tid" ] && return 1
  state_id=$(linear_query "{ team(id: \"$tid\") { states { nodes { id name } } } }" \
    | jq -r --arg s "$state_name" '.data.team.states.nodes[] | select(.name==$s) | .id' | head -1)
  [ -z "$state_id" ] && { log "WARN: could not resolve Linear state '$state_name'"; return 1; }
  linear_query "mutation { issueUpdate(id: \"$issue_uuid\", input: { stateId: \"$state_id\" }) { success } }" >/dev/null
}

comment_on_issue() {
  local issue_uuid="$1" body="$2"
  local esc; esc=$(jq -Rs . <<<"$body")
  linear_query "mutation { commentCreate(input: { issueId: \"$issue_uuid\", body: $esc }) { success } }" >/dev/null
}

# Escalation: a CodeRabbit finding the agents could not service becomes its own
# Linear issue, linked back to the parent, for the morning review queue.
create_linear_issue() {
  local title="$1" body="$2" parent_uuid="${3:-}"
  local tid; tid=$(team_uuid); [ -z "$tid" ] && { log "WARN: no team UUID; cannot escalate"; return 1; }
  local t b p
  t=$(jq -Rs . <<<"$title"); b=$(jq -Rs . <<<"$body")
  p=""; [ -n "$parent_uuid" ] && p=", parentId: \"$parent_uuid\""
  linear_query "mutation { issueCreate(input: { teamId: \"$tid\", title: $t, description: $b$p }) { success issue { identifier url } } }" \
    | jq -r '.data.issueCreate.issue | "\(.identifier) \(.url)"'
}

# ---- Stacked-PR merge order --------------------------------------------------

# Walks open PRs from the one based on development upward, so reviewers get an
# explicit bottom-up merge order instead of reverse-engineering the stack.
merge_sequence() {
  gh pr list --state open --json number,title,headRefName,baseRefName 2>/dev/null | jq -r '
    . as $prs
    | def walk($cur):
        if $cur == null then empty
        else "\($cur.number)\t\($cur.headRefName)\t\($cur.title)",
             walk($prs | map(select(.baseRefName == $cur.headRefName)) | first)
        end;
      walk($prs | map(select(.baseRefName == "development")) | first)
  ' | awk -F'\t' '{printf "%d. **#%s** `%s` — %s\n", NR, $1, $2, substr($3,1,60)}'
}

post_merge_sequence() {
  local pr_number="$1" seq
  seq=$(merge_sequence); [ -z "$seq" ] && return 0
  gh pr comment "$pr_number" --body "### Stacked PR — approve and merge in this order

$seq

Merge strictly top-to-bottom. Each PR shows only its own diff, and GitHub
retargets the next one to \`development\` automatically as its parent merges
(head branches are auto-deleted). Merging out of order will conflict.

Per PR: read the CodeRabbit review → check any escalated Linear issues → approve → squash-merge." >/dev/null 2>&1 \
    && log "Posted merge sequence on PR #$pr_number."
}

# ---- Rate limit detection ---------------------------------------------------

extract_reset_epoch() {
  local output="$1" reset_str
  reset_str=$(echo "$output" | grep -ioE "resets? at [0-9:apm ]+" | head -1 | sed -E 's/resets? at //I')
  if [ -n "$reset_str" ]; then
    date -j -f "%I:%M%p" "$(echo "$reset_str" | tr -d ' ' | tr 'a-z' 'A-Z')" "+%s" 2>/dev/null || true
  fi
}

# Only trust the CLI's own error envelope. Grepping the whole transcript for
# "rate limit" false-positives on any issue that is *about* rate limiting — in
# Aegis that threw away two successful runs and slept 5h each time. AssetAuditor
# has AA-16 (LiteLLM rate caps), which would trip exactly that bug.
is_rate_limited() {
  local logfile="$1"
  [ -f "$logfile" ] || return 1
  [ "$(jq -r '.is_error // false' "$logfile" 2>/dev/null)" = "true" ] || return 1
  jq -r '.result // ""' "$logfile" 2>/dev/null \
    | grep -qiE "usage limit|rate limit|reached your.*limit"
}

# ---- Claude invocation -------------------------------------------------------

run_agent() {
  local prompt="$1" logfile="$2" model="$3" tools="${4:-$ALLOWED_TOOLS}"
  local -a model_flag=()
  [ -n "$model" ] && model_flag=(--model "$model")
  # macOS ships bash 3.2, where "${arr[@]}" on an EMPTY array under `set -u` is an
  # unbound-variable fatal — which would kill every run, since no model override is
  # the default. ${arr[@]+"${arr[@]}"} is the 3.2-safe expansion. Do not "simplify".
  claude -p "$prompt" \
    --output-format json \
    --allowedTools "$tools" \
    --permission-mode acceptEdits \
    --max-turns "$MAX_TURNS" \
    --max-budget-usd "$MAX_BUDGET_USD" \
    ${model_flag[@]+"${model_flag[@]}"} \
    > "$logfile" 2>&1
}

# ---- CodeRabbit gate ---------------------------------------------------------

# `--agent` output shape is not a stable contract, so parse defensively: whole
# JSON, then NDJSON, then plain text. A parse failure must never look like
# "zero findings" — that would let unreviewed code masquerade as clean.
cr_normalise() {
  local f="$1"
  # -s (slurp) ALWAYS, not just for NDJSON: it collapses one-or-many JSON documents
  # into exactly one array. Running plain `jq` over an NDJSON file emits one result
  # per document, so the count downstream came back as "1\n0" and blew up the
  # caller's integer test. One input shape in, one array out.
  jq -sc '[.[] | .. | objects
          | select((has("severity") or has("level") or has("priority"))
                   and (has("message") or has("title") or has("description")))]' "$f" 2>/dev/null
}

cr_blocking_count() {
  local f="$1" norm n
  [ -s "$f" ] || { echo 0; return 0; }
  if norm=$(cr_normalise "$f") && [ -n "$norm" ] && [ "$norm" != "null" ] && [ "$norm" != "[]" ]; then
    n=$(printf '%s' "$norm" | jq --arg re "$CR_BLOCKING" \
      '[.[] | ((.severity // .level // .priority) | tostring | ascii_downcase) | select(test($re))] | length' 2>/dev/null)
    n=$(printf '%s' "${n:-}" | head -1 | tr -dc '0-9')
    [ -n "$n" ] && { echo "$n"; return 0; }
  fi
  # Text fallback: count lines naming a blocking severity. `grep -c` already prints
  # 0 when nothing matches but exits 1, so `|| true` — NOT `|| echo 0`, which would
  # emit a second line and hit the same integer-test bug from the other direction.
  n=$(grep -ciE "(${CR_BLOCKING})" "$f" 2>/dev/null || true)
  n=$(printf '%s' "${n:-0}" | head -1 | tr -dc '0-9')
  echo "${n:-0}"
}

# Sets: CR_STATUS (clean|resolved|escalated|unavailable), CR_SUMMARY, CR_ESCALATED
# The `complete` event carries the authoritative finding count. Severity-based
# counting alone can report "0 blocking" for a review that raised findings whose
# shape we failed to classify — which would print "clean" on a PR that is not.
cr_total_findings() {
  local f="$1" n norm
  n=$(jq -sr '[.[] | select(.type=="complete") | .findings] | last // empty' "$f" 2>/dev/null)
  n=$(printf '%s' "${n:-}" | head -1 | tr -dc '0-9')
  [ -n "$n" ] && { echo "$n"; return 0; }
  norm=$(cr_normalise "$f")
  n=$(printf '%s' "${norm:-[]}" | jq 'length' 2>/dev/null | head -1 | tr -dc '0-9')
  echo "${n:-0}"
}

coderabbit_gate() {
  local identifier="$1" issue_uuid="$2" base_ref="$3" title="$4"
  CR_STATUS="clean"; CR_SUMMARY=""; CR_ESCALATED=""

  if ! command -v coderabbit >/dev/null; then
    CR_STATUS="unavailable"; CR_SUMMARY="CodeRabbit CLI not installed — this branch was NOT machine-reviewed."
    return 0
  fi

  local round=0 findings blocking sleep_guard=0
  while [ "$round" -le "$CR_MAX_ROUNDS" ]; do
    findings="$LOG_DIR/${identifier}_coderabbit_r${round}.json"
    log "$identifier: CodeRabbit review (round $round) against $base_ref..."
    # -c CLAUDE.md gives the reviewer the project's standards, so findings land in
    # AssetAuditor's terms (provenance, masking, Decimal, raw-SQL discipline).
    coderabbit review --agent --committed --base "$base_ref" -c CLAUDE.md > "$findings" 2>&1
    local cr_exit=$?

    # A non-zero exit is ambiguous: some review CLIs exit non-zero precisely BECAUSE
    # they found issues. So only call it unavailable when the output also carries
    # nothing parseable — otherwise an auth error printed to stdout would sail
    # through the counter as "0 blocking findings" and a PR would claim it was
    # reviewed clean when it was never reviewed at all.
    if [ "$cr_exit" -ne 0 ]; then
      local shape textsev
      shape=$(cr_normalise "$findings")
      textsev=$(grep -ciE "(${CR_BLOCKING})" "$findings" 2>/dev/null || true)
      if { [ -z "$shape" ] || [ "$shape" = "[]" ]; } && [ "${textsev:-0}" -eq 0 ]; then
        log "$identifier: CodeRabbit failed to run (exit $cr_exit, no parseable findings)."
        CR_STATUS="unavailable"
        CR_SUMMARY="CodeRabbit could not run (exit $cr_exit). This branch was **NOT machine-reviewed** — review it by hand. Output: \`ops/logs/$(basename "$findings")\`"
        return 0
      fi
      log "$identifier: CodeRabbit exited $cr_exit but produced findings; continuing with the gate."
    fi

    blocking=$(cr_blocking_count "$findings")
    log "$identifier: CodeRabbit round $round — $blocking blocking finding(s)."

    if [ "${blocking:-0}" -eq 0 ]; then
      local total; total=$(cr_total_findings "$findings")
      if [ "${total:-0}" -gt 0 ]; then
        # Findings exist but none classified blocking: real nits, or a severity shape
        # we could not read. Either way this is not "clean" — say so on the PR.
        CR_STATUS="advisory"
        CR_SUMMARY="CodeRabbit reported **$total finding(s)**, none classified as blocking (${CR_BLOCKING//|/, })$([ "$round" -gt 0 ] && echo " after $round fix round(s)"). Read them before approving: \`ops/logs/$(basename "$findings")\`"
      else
        [ "$round" -eq 0 ] && CR_STATUS="clean" || CR_STATUS="resolved"
        CR_SUMMARY="CodeRabbit: reviewed, no findings$([ "$round" -gt 0 ] && echo " after $round fix round(s)")."
      fi
      return 0
    fi

    if [ "$round" -eq "$CR_MAX_ROUNDS" ]; then break; fi
    round=$((round+1))

    log "$identifier: sending findings back to the implementing agent (round $round)."
    comment_on_issue "$issue_uuid" "🐇 CodeRabbit raised $blocking blocking finding(s); agent is reworking (round $round/$CR_MAX_ROUNDS)."
    local fixlog="$LOG_DIR/${identifier}_fix_r${round}.json"
    run_agent "CodeRabbit reviewed your implementation of $identifier ($title) and raised blocking findings.

Take this review seriously. Fix the underlying pattern, not the symptom.

Findings:
$(head -c 12000 "$findings")

Rules:
- Do NOT silence a finding by disabling a lint rule, adding an ignore comment, or loosening a type.
- If a finding points at a pattern you used in several places, fix every instance.
- Re-run the tests and the linter afterwards; they must pass.
- Commit with: fix($identifier): address CodeRabbit round $round
- If a specific finding is genuinely wrong, out of scope for $identifier, or would
  violate the repo's own rules in CLAUDE.md, do NOT force a fix. Instead append your
  reasoning for that finding to CR_DISPUTE.md in the repo root (do not commit it).
  A mediator agent will adjudicate it." "$fixlog" "$IMPL_MODEL"

    # A usage limit inside a fix round is not a clean round: the findings are still
    # there and the branch is half-fixed. Sleep and redo this same round rather than
    # letting the loop conclude the code improved.
    if is_rate_limited "$fixlog"; then
      sleep_guard=$((sleep_guard+1))
      if [ "$sleep_guard" -gt 3 ]; then
        log "$identifier: rate-limited 3x inside the CodeRabbit gate — stopping the gate."
        CR_STATUS="escalated"
        CR_SUMMARY="Usage limits repeatedly interrupted the CodeRabbit fix rounds; $blocking blocking finding(s) were left unaddressed. **Review this PR by hand.**"
        return 0
      fi
      local rs; rs=$(extract_reset_epoch "$(cat "$fixlog")")
      local ws=$((5*3600)); [ -n "$rs" ] && ws=$(( rs - $(date +%s) )); [ "$ws" -lt 0 ] && ws=$((5*3600))
      log "$identifier: usage limit during fix round $round — sleeping $((ws/60))m, then redoing this round."
      comment_on_issue "$issue_uuid" "⏸️ Usage limit reached mid-CodeRabbit-rework. Auto-resuming after the window resets."
      sleep "$ws"
      round=$((round-1))
    fi
  done

  # Blocking findings survived the fix rounds → mediator adjudicates.
  log "$identifier: $blocking blocking finding(s) survived $CR_MAX_ROUNDS rounds — invoking mediator."
  local medlog="$LOG_DIR/${identifier}_mediator.json"
  rm -f "$REPO_DIR/MEDIATION_OUT.json"
  run_agent "You are the mediator for Linear issue $identifier ($title). You are NOT the implementer.

The implementing agent has had $CR_MAX_ROUNDS attempts at CodeRabbit's blocking findings and some remain.

Surviving findings:
$(head -c 12000 "$findings")

The implementer's disputes (may be absent):
$(head -c 6000 "$REPO_DIR/CR_DISPUTE.md" 2>/dev/null || echo '(none written)')

Read the actual code before judging — CodeRabbit can be wrong, and the implementer can be
wrong about CodeRabbit being wrong. Weigh every finding against docs/adr/ADR_v1.1.0.md and
CLAUDE.md (provenance-first, masking before any LLM call, Decimal for money, parameterized
raw SQL only, RLS everywhere, zero-cost contract).

For each surviving blocking finding decide exactly one verdict:
  fixed_now      — small, safe, in scope: make the fix yourself now and commit it
                   (message: fix($identifier): mediator resolves CodeRabbit finding)
  escalate       — legitimate but too large or out of scope for $identifier: it becomes
                   its own Linear issue for the human to triage in the morning
  false_positive — CodeRabbit is wrong: say precisely why
  accepted_risk  — real but deliberately accepted here: say why, and what would change it

Then write /MEDIATION_OUT.json in the repo root (do NOT commit it) with exactly this shape:
{\"verdicts\":[{\"finding\":\"one-line summary\",\"file\":\"path:line\",\"severity\":\"major\",
\"verdict\":\"escalate\",\"rationale\":\"...\",\"issue_title\":\"...\",\"issue_body\":\"...\"}]}
issue_title/issue_body are required only for escalate verdicts; write them as a
self-contained issue an agent could pick up cold (file paths, what good looks like).

Be decisive. Do not escalate something you can safely fix in three lines, and do not
fix something that needs a design decision." "$medlog" "$MEDIATOR_MODEL"

  local med="$REPO_DIR/MEDIATION_OUT.json"
  if [ ! -f "$med" ] || ! jq -e . "$med" >/dev/null 2>&1; then
    log "$identifier: mediator produced no usable verdict file."
    CR_STATUS="escalated"
    CR_SUMMARY="$blocking blocking CodeRabbit finding(s) survived $CR_MAX_ROUNDS rounds and the mediator returned no verdict. **Review this PR by hand.** Findings: \`$(basename "$findings")\`"
    return 0
  fi

  local n_esc=0 esc_lines=""
  while IFS= read -r row; do
    local v t b f
    v=$(jq -r '.verdict' <<<"$row"); f=$(jq -r '.finding' <<<"$row")
    [ "$v" != "escalate" ] && continue
    t=$(jq -r '.issue_title // empty' <<<"$row"); [ -z "$t" ] && t="CodeRabbit follow-up from $identifier: $f"
    b=$(jq -r '.issue_body // empty' <<<"$row")
    b="$b

---
Escalated automatically by the overnight orchestrator from **$identifier**.
CodeRabbit severity: $(jq -r '.severity // "unknown"' <<<"$row") · Location: \`$(jq -r '.file // "unknown"' <<<"$row")\`
Mediator rationale: $(jq -r '.rationale // ""' <<<"$row")"
    local created; created=$(create_linear_issue "$t" "$b" "$issue_uuid")
    if [ -n "$created" ]; then
      n_esc=$((n_esc+1)); esc_lines="$esc_lines
- $created — $f"
      log "$identifier: escalated → $created"
    fi
  done < <(jq -c '.verdicts[]?' "$med")

  local dismissed
  dismissed=$(jq -r '[.verdicts[]? | select(.verdict=="false_positive" or .verdict=="accepted_risk")
                      | "- **\(.verdict)** \(.finding) — \(.rationale)"] | join("\n")' "$med")
  local fixed
  fixed=$(jq -r '[.verdicts[]? | select(.verdict=="fixed_now") | "- \(.finding)"] | join("\n")' "$med")

  CR_ESCALATED="$esc_lines"
  CR_STATUS=$([ "$n_esc" -gt 0 ] && echo "escalated" || echo "resolved")
  CR_SUMMARY="CodeRabbit gate: $blocking blocking finding(s) survived $CR_MAX_ROUNDS agent fix rounds; mediator adjudicated.
$([ -n "$fixed" ] && printf 'Fixed by mediator:\n%s\n' "$fixed")
$([ -n "$esc_lines" ] && printf 'Escalated to Linear (triage in the morning):%s\n' "$esc_lines")
$([ -n "$dismissed" ] && printf 'Dismissed with rationale:\n%s\n' "$dismissed")"
  rm -f "$med" "$REPO_DIR/CR_DISPUTE.md"
  return 0
}

# Best-effort: pull CodeRabbit's SaaS review of the opened PR into Linear, so the
# morning read starts from the same place whether you open Linear or GitHub.
cr_pr_followup() {
  local pr_number="$1" issue_uuid="$2"
  command -v coderabbit >/dev/null || return 0
  local out="$LOG_DIR/pr_${pr_number}_coderabbit.txt"
  # --show-prompts is REQUIRED by this subcommand; --agent alone exits with a usage
  # error (observed on PR #1). Also note CodeRabbit refuses closed PRs, so this is
  # best-effort by design and never gates anything.
  if coderabbit pullrequest "$pr_number" --show-prompts --agent > "$out" 2>&1 && [ -s "$out" ]; then
    comment_on_issue "$issue_uuid" "🐇 CodeRabbit PR review (#$pr_number) excerpt:
\`\`\`
$(head -c 3000 "$out")
\`\`\`"
  fi
}

# ---- Core: run one issue ----------------------------------------------------

run_issue() {
  local identifier="$1"
  log "Fetching $identifier from Linear..."
  local issue_json title description issue_uuid
  issue_json=$(resolve_issue "$identifier")
  issue_uuid=$(jq -r '.id // empty' <<<"$issue_json")
  title=$(jq -r '.title // empty' <<<"$issue_json")
  description=$(jq -r '.description // ""' <<<"$issue_json")

  if [ -z "$issue_uuid" ]; then
    log "ERROR: could not resolve $identifier in Linear, skipping"
    return 2
  fi

  local branch="feature/$(echo "$identifier" | tr '[:upper:]' '[:lower:]')"

  cd "$REPO_DIR" || { log "ERROR: REPO_DIR not found"; return 2; }

  # Agents routinely leave uncommitted edits behind. Without wiping them the
  # checkout below fails, and since we don't run with `set -e` the script would
  # carry on and cut this issue's branch off the *previous* issue's branch.
  # `clean -fd` (no -x) leaves .gitignore'd orchestrator state alone.
  git reset --hard -q
  git clean -fd -q

  # Stacked-PR base selection: if the previous issue's branch exists and is not
  # yet merged into development, cut from it so this agent can build on that
  # (unmerged) work and the PR diff stays incremental.
  git fetch origin --prune --quiet
  local base_branch="development" base_ref="origin/development"
  if [ -n "${LAST_BRANCH:-}" ] && git rev-parse --verify "origin/$LAST_BRANCH" >/dev/null 2>&1; then
    if git merge-base --is-ancestor "origin/$LAST_BRANCH" origin/development 2>/dev/null; then
      log "$identifier: dependency $LAST_BRANCH already merged into development; basing on development."
    else
      base_branch="$LAST_BRANCH"; base_ref="origin/$LAST_BRANCH"
      log "$identifier: stacking on unmerged dependency $LAST_BRANCH."
    fi
  fi

  if ! git checkout -B "$branch" "$base_ref" --quiet; then
    log "ERROR: could not cut $branch from $base_ref. Skipping $identifier."
    return 2
  fi
  local on_branch; on_branch=$(git rev-parse --abbrev-ref HEAD)
  if [ "$on_branch" != "$branch" ]; then
    log "ERROR: expected HEAD on $branch but it is $on_branch. Skipping $identifier."
    return 2
  fi

  set_issue_state "$issue_uuid" "In Progress"
  comment_on_issue "$issue_uuid" "🤖 Overnight agent starting on branch \`$branch\` (base \`$base_branch\`)."

  local contracts=""
  if [ -s "$CONTRACTS_FILE" ]; then
    contracts="
## Contracts from upstream agents (already on this branch)

Committed on the branch you are on but still awaiting human review. Treat these as
settled interfaces: import and build on them, do not reimplement or refactor them.

$(cat "$CONTRACTS_FILE")
"
  fi

  local pg_note="PostgreSQL is NOT available locally; write DB code and tests but say plainly in your summary what could not be executed."
  pg_isready -q 2>/dev/null && pg_note="PostgreSQL 16 is on localhost:5432 (superuser '$(whoami)'); create your own scratch database. Prefer a real integration test over mocking for DB behaviour."

  local prompt="You are implementing Linear issue $identifier: $title

Description:
$description
$contracts
## How to work

Read CLAUDE.md first — it is binding. The planning artifacts in this repo are the
source of truth: docs/adr/ADR_v1.1.0.md is the architecture of record, mvp.md holds
the issue specs and dependency spine, data/samples/README.md holds the golden numbers
that tests must reproduce, and skills/e2e-testing/SKILL.md defines acceptance flows.

Implement this issue fully within the existing repo conventions. Write tests. Run the
test suite and the linter before you finish. Do not touch files outside the scope of
this issue. Commit your work with a conventional-commit message referencing $identifier.
Do NOT push and do NOT open a pull request — the orchestrator does that after a
CodeRabbit review gate.

## Environment

$pg_note
Docker: $(docker info >/dev/null 2>&1 && echo 'daemon running' || echo 'installed but NOT running — do not depend on containers').
Available: pytest, ruff, mypy, python3, uv, pip, npm/npx/node ($(node -v 2>/dev/null)), psql,
createdb/dropdb, pip-audit, gitleaks, trivy, git, gh, jq, docker.
You do NOT have curl and there are no cloud credentials on this machine: no Supabase
project, no Vercel token, no Groq key, no GPU box. For anything needing them, write the
code, config, migrations and runbook, prove what you can locally, and state plainly in
your summary what is unverified. Never fake a passing test and never invent a credential.
To exercise HTTP routes use FastAPI's TestClient or httpx inside pytest.

## Definition of done

Tests pass, linter clean, work committed on this branch, and a contract block appended
to CONTRACT_OUT.md in the repo root (do NOT commit that file): module paths, key
classes/functions with signatures, new DB tables or columns. Under 20 lines. Downstream
agents build against it.

Your work will be reviewed by CodeRabbit before a PR is opened. Write it to survive that."

  local logfile="$LOG_DIR/${identifier}_$(date +%s).json"
  log "Running implementing agent for $identifier (branch $branch)..."
  run_agent "$prompt" "$logfile" "$IMPL_MODEL"
  local exit_code=$?
  local output; output=$(cat "$logfile")

  if is_rate_limited "$logfile"; then
    log "Hit usage limit while working on $identifier."
    local resume_epoch; resume_epoch=$(extract_reset_epoch "$output")
    local wait_secs=$((5*3600))
    if [ -n "$resume_epoch" ]; then
      wait_secs=$(( resume_epoch - $(date +%s) )); [ "$wait_secs" -lt 0 ] && wait_secs=$((5*3600))
    fi
    log "Sleeping $((wait_secs/60)) minutes until the window resets..."
    comment_on_issue "$issue_uuid" "⏸️ Agent paused: usage limit reached. Auto-resuming this issue after the window resets."
    sleep "$wait_secs"
    return 1  # caller retries this same issue
  fi

  if [ "$exit_code" -ne 0 ]; then
    log "$identifier failed (exit $exit_code). Log: $logfile"
    comment_on_issue "$issue_uuid" "⚠️ Overnight agent run failed (exit $exit_code). Needs a human. Log excerpt:
\`\`\`
$(echo "$output" | tail -30)
\`\`\`"
    set_issue_state "$issue_uuid" "Backlog"
    report "- ❌ **$identifier** — agent failed (exit $exit_code). Log: \`ops/logs/$(basename "$logfile")\`"
    return 2
  fi

  # Agents sometimes create a branch of their own and commit there. Pushing
  # "$branch" in that case ships whatever it inherited, not the work.
  local head_after; head_after=$(git rev-parse --abbrev-ref HEAD)
  if [ "$head_after" != "$branch" ]; then
    log "$identifier: agent left HEAD on '$head_after', not '$branch'. Not pushing."
    comment_on_issue "$issue_uuid" "⚠️ Agent committed on \`$head_after\` instead of \`$branch\`. Work is local only; no PR opened."
    set_issue_state "$issue_uuid" "Backlog"
    report "- ❌ **$identifier** — agent committed on the wrong branch (\`$head_after\`). Nothing pushed."
    return 2
  fi

  if ! git log "$base_ref".."$branch" --oneline | grep -q .; then
    log "$identifier produced no commits — treating as incomplete."
    set_issue_state "$issue_uuid" "Backlog"
    comment_on_issue "$issue_uuid" "⚠️ Agent run completed but produced no commits. Needs a human look."
    report "- ❌ **$identifier** — no commits produced."
    return 2
  fi

  # ---- CodeRabbit gate before anything is pushed ----
  coderabbit_gate "$identifier" "$issue_uuid" "$base_ref" "$title"
  log "$identifier: CodeRabbit gate status = $CR_STATUS"

  if [ "$CR_STATUS" = "unavailable" ] && [ "$CR_REQUIRED" = "1" ]; then
    log "$identifier: CR_REQUIRED=1 and CodeRabbit unavailable — refusing to push."
    comment_on_issue "$issue_uuid" "⛔ Held back: CodeRabbit could not review this branch and CR_REQUIRED=1. Work is committed locally on \`$branch\`."
    set_issue_state "$issue_uuid" "Backlog"
    report "- ⛔ **$identifier** — held: CodeRabbit unavailable, nothing pushed."
    return 2
  fi

  # The mediator commits its own fixes, but may leave an edit unstaged. `add -u`
  # (tracked files only) rather than `add -A`: an unattended run must never sweep
  # a stray scratch file the agent forgot into a reviewed PR.
  git add -u >/dev/null 2>&1
  git diff --cached --quiet || git commit -q -m "fix($identifier): mediator adjustments from CodeRabbit gate"
  local stray; stray=$(git ls-files --others --exclude-standard | head -5)
  [ -n "$stray" ] && log "$identifier: note — untracked files left behind, NOT committed: $(echo "$stray" | tr '\n' ' ')"

  git push -u origin "$branch" --quiet
  local stack_note=""
  [ "$base_branch" != "development" ] && stack_note="

> **Stacked PR.** Based on \`$base_branch\` ($LAST_ISSUE), still awaiting review.
> GitHub retargets this to \`development\` automatically once the parent merges.
> Review the parent first."

  local cr_badge
  case "$CR_STATUS" in
    clean)       cr_badge="✅ CodeRabbit: clean on first review." ;;
    resolved)    cr_badge="✅ CodeRabbit: blocking findings resolved before this PR opened." ;;
    advisory)    cr_badge="📝 CodeRabbit: non-blocking findings recorded — read before approving." ;;
    escalated)   cr_badge="⚠️ CodeRabbit: findings escalated to Linear — read before approving." ;;
    unavailable) cr_badge="⛔ CodeRabbit did NOT review this branch. Treat as unreviewed." ;;
  esac

  local pr_url
  pr_url=$(gh pr create --title "$identifier: $title" \
    --body "Automated implementation of $identifier by the overnight orchestrator. **Human review required — this will not auto-merge.**$stack_note

### CodeRabbit gate
$cr_badge

$CR_SUMMARY

### Review order
See the stacked-merge comment below. Approve and squash-merge bottom-up.

_Spec: \`mvp.md\` ($identifier) · Architecture: \`docs/adr/ADR_v1.1.0.md\`_" \
    --base "$base_branch" --head "$branch" 2>&1 | tail -1)

  local pr_number; pr_number=$(basename "$pr_url")
  post_merge_sequence "$pr_number"
  cr_pr_followup "$pr_number" "$issue_uuid"

  comment_on_issue "$issue_uuid" "✅ Agent finished. PR: $pr_url (base \`$base_branch\`) — awaiting human review, will NOT auto-merge.

$CR_SUMMARY"
  set_issue_state "$issue_uuid" "In Review"
  echo "$identifier" >> "$STATE_FILE"
  log "$identifier done -> $pr_url"

  local rep_icon="✅"; [ "$CR_STATUS" = "advisory" ] && rep_icon="📝"; [ "$CR_STATUS" = "escalated" ] && rep_icon="⚠️"; [ "$CR_STATUS" = "unavailable" ] && rep_icon="⛔"
  report "- $rep_icon **$identifier** $title — $pr_url (base \`$base_branch\`) · CodeRabbit: $CR_STATUS$CR_ESCALATED"

  if [ -f "$REPO_DIR/CONTRACT_OUT.md" ]; then
    { echo ""; echo "### $identifier — $title"; echo "_Branch \`$branch\`, PR $pr_url, awaiting merge._"; echo ""
      cat "$REPO_DIR/CONTRACT_OUT.md"; } >> "$CONTRACTS_FILE"
    rm -f "$REPO_DIR/CONTRACT_OUT.md"
    log "$identifier: contract recorded for downstream agents."
  else
    log "$identifier: WARNING — no CONTRACT_OUT.md; downstream agents get no interface summary."
  fi

  LAST_BRANCH="$branch"; LAST_ISSUE="$identifier"
  return 0
}

# ---- Main loop ---------------------------------------------------------------

preflight

report ""
report "# Night report — $(date '+%Y-%m-%d %H:%M')"
report ""
log "Starting AssetAuditor orchestrator. Repo: $REPO_DIR · Team: $LINEAR_TEAM_KEY"

while IFS=$'\t' read -r tier identifier parallel; do
  [[ "$tier" =~ ^#.*$ || -z "${tier:-}" ]] && continue
  grep -qx "$identifier" "$STATE_FILE" && { log "Skipping $identifier (already done)"; continue; }

  # Tier 4 holds the kill gate: deterministic PDF parsing. If a text-layer bank
  # statement cannot be parsed into the same rows as its CSV fixture, the whole
  # "upload your statements" premise is unproven and the tiers above it are waste.
  if [ "$tier" = "4" ] && [ "${KILL_GATE_ISSUE:-}" = "$identifier" ]; then
    log "*** KILL GATE ($identifier): statement parsing must reproduce the fixture rows. ***"
  fi

  attempts=0; failed=0
  until run_issue "$identifier"; do
    rc=$?
    attempts=$((attempts+1))
    if [ "$rc" -eq 2 ]; then
      log "$identifier needs a human, moving on (not retrying automatically)."
      failed=1; break
    fi
    if [ "$attempts" -ge 3 ]; then
      log "$identifier: rate-limited 3x in a row — stopping for a human check."
      report ""; report "Loop stopped early: $identifier rate-limited three times."
      exit 1
    fi
    # rc == 1: rate limit, already slept inside run_issue; retry same issue
  done

  if [ "${KILL_GATE_ISSUE:-}" = "$identifier" ] && [ "$failed" -eq 1 ]; then
    log "*** KILL GATE FAILED ($identifier). Stopping before later tiers spend more budget."
    log "*** Reassess parsing feasibility, then re-run. Set SKIP_KILL_GATE=1 to override. ***"
    report ""; report "**KILL GATE FAILED at $identifier** — deterministic statement parsing is unproven. Later tiers were not attempted."
    [ "${SKIP_KILL_GATE:-0}" = "1" ] || exit 1
  fi
done < "$QUEUE_FILE"

report ""
report "## Merge order for this morning"
report ""
merge_sequence >> "$REPORT_FILE" 2>/dev/null || report "_(no open PRs)_"
report ""
report "Approve and squash-merge bottom-up. For each PR: read the CodeRabbit review → check escalated Linear issues → approve → merge. GitHub retargets the child PR automatically and deletes the head branch."

log "Queue exhausted. Night report: $REPORT_FILE"
