#!/usr/bin/env bash
# AssetAuditor overnight orchestrator
# Runs Claude Code headlessly against Linear backlog issues in dependency order,
# gates every branch through CodeRabbit before a PR is opened, mediates findings
# the implementing agent cannot service, and self-resumes after usage-limit windows.
#
# Nothing here ever merges. Human review on `development` is the only merge gate.
#
# Prereqs (all checked by preflight below):
#   - `claude` CLI logged in            (claude login)
#   - `gh` CLI authenticated             (gh auth login)
#   - `coderabbit` CLI authenticated     (coderabbit auth login)
#   - LINEAR_API_KEY + LINEAR_TEAM_KEY exported
#   - ops/queue.tsv generated by ops/seed_linear.py
#   - repo bootstrapped by ops/bootstrap_repo.sh (main + development + origin)
#
# Run inside tmux so it survives the laptop closing:
#   tmux new -s assetauditor
#   export LINEAR_API_KEY=lin_api_...  LINEAR_TEAM_KEY=ASA
#   ./ops/orchestrator.sh
#   (ctrl-b, d to detach; tmux attach -t assetauditor to check back in)

set -uo pipefail

# ---- Self-relocation ---------------------------------------------------------
# This script mutates the very worktree it lives in: run_issue() runs
# `git reset --hard`, `git clean -fd` and `git checkout -B`, all of which replace
# ops/*.sh with whatever version the target branch happens to carry — while bash
# is still reading this file incrementally. That silently runs a different script
# than the one you launched, and deletes outright any ops script not yet committed
# on that branch. Re-exec from a copy outside the repo so the running code can
# never change underneath us. State (logs, queue, contracts) stays in the real
# repo via AA_REAL_OPS; all of it is gitignored, so `git clean -fd` spares it.
if [ "${AA_RELOCATED:-0}" != "1" ] && [ "${ORCHESTRATOR_LIB_ONLY:-0}" != "1" ]; then
  _src="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  _run="${TMPDIR:-/tmp}/aa-ops-$$"
  mkdir -p "$_run" && cp "$_src"/*.sh "$_run"/ 2>/dev/null
  export AA_RELOCATED=1 AA_REAL_OPS="$_src"
  export REPO_DIR="${REPO_DIR:-$(cd "$_src/.." && pwd)}"
  exec bash "$_run/$(basename "${BASH_SOURCE[0]}")" "$@"
fi

OPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_HOME="${AA_REAL_OPS:-$OPS_DIR}"   # state lives in the repo, code may not
REPO_DIR="${REPO_DIR:-$(cd "$OPS_DIR/.." && pwd)}"
QUEUE_FILE="${QUEUE_FILE:-$STATE_HOME/queue.tsv}"
LOG_DIR="$STATE_HOME/logs"
STATE_FILE="$STATE_HOME/.completed_issues"
CONTRACTS_FILE="$STATE_HOME/.agent_contracts.md"
REPORT_FILE="$LOG_DIR/NIGHT_REPORT.md"

MAX_TURNS="${MAX_TURNS:-120}"
# Model split, by the kind of thinking the call needs:
#   IMPL_MODEL     — writing code against a spec that already exists: the implementing
#                    agent, the CodeRabbit fix rounds, the sweeper's and remediator's
#                    fixers. Bulk of the tokens, so this is the cheaper tier.
#   MEDIATOR_MODEL — adjudicating disputed findings: decides fix vs dismiss vs escalate,
#                    and writes the rationale a human reads later. Judgement, not typing.
# There is no per-issue budget cap; the account spend limit is the only ceiling, and
# is_spend_capped() halts the run cleanly when it is reached.
IMPL_MODEL="${IMPL_MODEL:-claude-sonnet-5}"
MEDIATOR_MODEL="${MEDIATOR_MODEL:-claude-opus-5}"
LINEAR_API="https://api.linear.app/graphql"
LINEAR_TEAM_KEY="${LINEAR_TEAM_KEY:-}"

# ---- CodeRabbit gate policy -------------------------------------------------
# Blocking findings go back to the implementing agent CR_MAX_ROUNDS times. What
# survives goes to a mediator agent, which either fixes it, dismisses it with a
# written rationale, or escalates it as a Linear issue for the morning review.
CR_MAX_ROUNDS="${CR_MAX_ROUNDS:-2}"
CR_BLOCKING="${CR_BLOCKING:-critical|major|blocker|high}"
# 1 = refuse to push when CodeRabbit itself cannot run. Default 0: still open the
# PR (human review is the real gate) but flag it loudly in the PR body, the Linear
# comment and the night report, so an unreviewed branch can never look reviewed.
CR_REQUIRED="${CR_REQUIRED:-0}"

# Explicit allowlist. Anything not named here is denied outright — headless runs
# never prompt, so a missing entry silently cripples the agent rather than
# pausing for a human. Deliberately excludes rm, sudo, and curl-to-anywhere
# (the orchestrator owns all Linear/network calls, so agents cannot exfiltrate).
ALLOWED_TOOLS="Read,Write,Edit,Grep,Glob,\
Bash(git:*),Bash(gh:*),\
Bash(pytest:*),Bash(ruff:*),Bash(mypy:*),Bash(python3:*),Bash(python:*),\
Bash(pip:*),Bash(pip3:*),Bash(uv:*),Bash(npm:*),Bash(npx:*),Bash(node:*),\
Bash(psql:*),Bash(pg_dump:*),Bash(pg_restore:*),Bash(createdb:*),Bash(dropdb:*),\
Bash(pg_isready:*),Bash(docker:*),Bash(docker-compose:*),\
Bash(pip-audit:*),Bash(gitleaks:*),Bash(trivy:*),\
Bash(mkdir:*),Bash(ls:*),Bash(cat:*),Bash(cp:*),Bash(mv:*),Bash(touch:*),\
Bash(echo:*),Bash(head:*),Bash(tail:*),Bash(wc:*),Bash(diff:*),Bash(jq:*),\
Bash(sed:*),Bash(grep:*),Bash(find:*),Bash(sort:*),Bash(awk:*),Bash(make:*)"

mkdir -p "$LOG_DIR"
touch "$STATE_FILE" "$CONTRACTS_FILE"

# Rolling pointer to the previous issue's branch, for stacked-PR bases.
# SEED_LAST_BRANCH lets a fresh run continue an existing stack instead of
# re-basing on development and losing the unmerged work below it.
LAST_BRANCH="${SEED_LAST_BRANCH:-}"
LAST_ISSUE="${SEED_LAST_ISSUE:-upstream}"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
report() { echo "$*" >> "$REPORT_FILE"; }

# ---- Review-debt ledger ------------------------------------------------------
# CodeRabbit's free tier allows 8 reviews per replenishing window — far fewer than
# this queue needs. Development must NEVER wait on it, so when the quota runs out
# we bank the unfinished review as debt and carry on. ops/review_sweeper.sh, run
# hourly by launchd, settles the debt when quota returns. Columns:
#   pr  branch  linear_id  state  recorded_epoch  attempts
# state: never_reviewed | unverified   (unverified = reviewed and fixed once, but
# the confirming re-review never ran, so the fixes are unconfirmed)
REVIEW_DEBT="$STATE_HOME/.review_debt.tsv"

# state: never_reviewed | unverified | reviewed_pending_fix
# reviewed_pending_fix means CodeRabbit HAS reviewed and its findings are saved in
# column 7 — only the Claude-powered fixer is outstanding. A later sweep reuses
# those findings instead of spending another review on the same branch.
record_review_debt() {
  local pr="$1" branch="$2" issue="$3" state="$4" findings="${5:-}"
  touch "$REVIEW_DEBT"
  awk -F'\t' -v b="$branch" '$2 != b' "$REVIEW_DEBT" > "$REVIEW_DEBT.tmp" 2>/dev/null
  mv -f "$REVIEW_DEBT.tmp" "$REVIEW_DEBT" 2>/dev/null
  printf '%s\t%s\t%s\t%s\t%s\t0\t%s\n' "$pr" "$branch" "$issue" "$state" "$(date +%s)" "$findings" >> "$REVIEW_DEBT"
  log "$issue: review debt recorded ($state) — the hourly sweeper will settle it."
}

# ---- Worktree lock -----------------------------------------------------------
# The hourly launchd sweeper and the tmux orchestrator share ONE git worktree and
# both run `git reset --hard` / `git checkout -B`. Without this, a sweep landing
# mid-issue would yank the branch out from under a running agent and commit its
# work onto the wrong branch. Whoever holds this lock owns the worktree.
WORKTREE_LOCK="$STATE_HOME/.worktree.lock"

acquire_worktree() {
  local max="${1:-900}" waited=0 age
  while ! mkdir "$WORKTREE_LOCK" 2>/dev/null; do
    age=$(( $(date +%s) - $(stat -f %m "$WORKTREE_LOCK" 2>/dev/null || echo 0) ))
    if [ "$age" -gt 3600 ]; then
      log "Stale worktree lock (${age}s) — reclaiming."
      rm -rf "$WORKTREE_LOCK" 2>/dev/null; continue
    fi
    if [ "$waited" -ge "$max" ]; then return 1; fi
    sleep 10; waited=$((waited+10))
  done
  date +%s > "$WORKTREE_LOCK/since" 2>/dev/null
  return 0
}

release_worktree() { rm -rf "$WORKTREE_LOCK" 2>/dev/null; }

clear_review_debt() {
  local branch="$1"
  [ -f "$REVIEW_DEBT" ] || return 0
  awk -F'\t' -v b="$branch" '$2 != b' "$REVIEW_DEBT" > "$REVIEW_DEBT.tmp" 2>/dev/null \
    && mv -f "$REVIEW_DEBT.tmp" "$REVIEW_DEBT" 2>/dev/null
}

# ---- Preflight ---------------------------------------------------------------
# Fail loudly at 22:00 rather than silently at 03:00 with eight broken branches.

preflight() {
  local fatal=0
  command -v claude     >/dev/null || { log "FATAL: claude CLI not found"; fatal=1; }
  command -v gh         >/dev/null || { log "FATAL: gh CLI not found"; fatal=1; }
  command -v jq         >/dev/null || { log "FATAL: jq not found"; fatal=1; }
  command -v coderabbit >/dev/null || { log "WARN: coderabbit CLI not found — gate will report 'unavailable'"; }

  gh auth status >/dev/null 2>&1 || { log "FATAL: gh not authenticated. Run: gh auth login"; fatal=1; }
  [ -n "$LINEAR_API_KEY" ]  || { log "FATAL: LINEAR_API_KEY not exported"; fatal=1; }
  [ -n "$LINEAR_TEAM_KEY" ] || { log "FATAL: LINEAR_TEAM_KEY not exported (e.g. ASA)"; fatal=1; }
  [ -f "$QUEUE_FILE" ]      || { log "FATAL: no queue at $QUEUE_FILE — run ops/seed_linear.py first"; fatal=1; }

  cd "$REPO_DIR" 2>/dev/null || { log "FATAL: REPO_DIR $REPO_DIR missing"; fatal=1; }
  git rev-parse --git-dir >/dev/null 2>&1 || { log "FATAL: $REPO_DIR is not a git repo — run ops/bootstrap_repo.sh"; fatal=1; }
  git rev-parse --verify origin/development >/dev/null 2>&1 \
    || { log "FATAL: origin/development missing — run ops/bootstrap_repo.sh"; fatal=1; }

  if command -v coderabbit >/dev/null && ! coderabbit auth status >/dev/null 2>&1; then
    log "WARN: coderabbit CLI is not authenticated (coderabbit auth login). Gate will flag every PR as unreviewed."
    [ "$CR_REQUIRED" = "1" ] && { log "FATAL: CR_REQUIRED=1 and CodeRabbit unusable"; fatal=1; }
  fi

  # Integration-test dependencies. Not fatal: agents are told what is unavailable
  # and must say so in their summary rather than faking a passing test.
  # `pg_isready` with no host probes the UNIX SOCKET in /tmp, which a Postgres
  # running in Docker never creates — it publishes TCP only. Checking the socket
  # alone reports "no PostgreSQL" against a perfectly healthy container, and every
  # agent would then skip its DB tests for no reason. Probe both transports, and
  # when only TCP answers, export PGHOST so psql/asyncpg in the agents connect there.
  pg_available() {
    pg_isready -q 2>/dev/null && return 0
    if pg_isready -q -h localhost -p 5432 2>/dev/null; then export PGHOST=localhost; return 0; fi
    return 1
  }

  if ! pg_available; then
    log "WARN: PostgreSQL not accepting connections. Attempting to start as the current user..."
    # Deliberately NOT `brew services start`: if that ever runs under sudo it
    # registers a ROOT LaunchDaemon, and PostgreSQL refuses to execute as root —
    # producing an invisible crash-restart loop (seen 2026-08-31, a 900KB log of
    # '"root" execution of the PostgreSQL server is not permitted'). Start it
    # directly as this user, logging somewhere this user can definitely write.
    pg_ctl -D "$(brew --prefix 2>/dev/null)/var/postgresql@16" \
           -l "$LOG_DIR/postgres.log" start >/dev/null 2>&1 || true
    sleep 3
    if pg_available; then
      log "PostgreSQL is up${PGHOST:+ (TCP at $PGHOST:5432)}."
    else
      log "WARN: no local PostgreSQL — DB-backed issues will write code and tests but report them unverified."
      log "      If a root LaunchDaemon is crash-looping, clear it: sudo launchctl bootout system/homebrew.mxcl.postgresql@16"
    fi
  fi
  docker info >/dev/null 2>&1 || log "WARN: Docker daemon not running — container-dependent work will be written but not run."
  local node_major
  node_major=$(node -v 2>/dev/null | sed -E 's/^v([0-9]+).*/\1/')
  [ -n "$node_major" ] && [ "$node_major" -lt 20 ] \
    && log "WARN: node $(node -v) — modern Vite needs node 20+. Frontend issues may need a node upgrade."

  [ "$fatal" -eq 1 ] && { log "Preflight failed. Nothing was run."; exit 1; }
  log "Preflight OK."
}

# ---- Linear GraphQL helpers -------------------------------------------------

linear_query() {
  local query="$1"
  curl -s -X POST "$LINEAR_API" \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg q "$query" '{query: $q}')"
}

# Resolve human-readable identifier (e.g. ASA-9) to Linear's internal UUID + state
resolve_issue() {
  local identifier="$1"
  linear_query "{ issues(filter: { number: { eq: ${identifier##*-} }, team: { key: { eq: \"${identifier%-*}\" } } }) { nodes { id identifier title description state { id name } } } }" \
    | jq -r '.data.issues.nodes[0]'
}

team_uuid() {
  linear_query "{ teams(filter: { key: { eq: \"$LINEAR_TEAM_KEY\" } }) { nodes { id } } }" \
    | jq -r '.data.teams.nodes[0].id // empty'
}

set_issue_state() {
  local issue_uuid="$1" state_name="$2"
  local tid state_id
  tid=$(team_uuid); [ -z "$tid" ] && return 1
  state_id=$(linear_query "{ team(id: \"$tid\") { states { nodes { id name } } } }" \
    | jq -r --arg s "$state_name" '.data.team.states.nodes[] | select(.name==$s) | .id' | head -1)
  [ -z "$state_id" ] && { log "WARN: could not resolve Linear state '$state_name'"; return 1; }
  linear_query "mutation { issueUpdate(id: \"$issue_uuid\", input: { stateId: \"$state_id\" }) { success } }" >/dev/null
}

comment_on_issue() {
  local issue_uuid="$1" body="$2"
  local esc; esc=$(jq -Rs . <<<"$body")
  linear_query "mutation { commentCreate(input: { issueId: \"$issue_uuid\", body: $esc }) { success } }" >/dev/null
}

# Escalation: a CodeRabbit finding the agents could not service becomes its own
# Linear issue, linked back to the parent, for the morning review queue.
create_linear_issue() {
  local title="$1" body="$2" parent_uuid="${3:-}"
  local tid; tid=$(team_uuid); [ -z "$tid" ] && { log "WARN: no team UUID; cannot escalate"; return 1; }
  local t b p
  t=$(jq -Rs . <<<"$title"); b=$(jq -Rs . <<<"$body")
  p=""; [ -n "$parent_uuid" ] && p=", parentId: \"$parent_uuid\""
  linear_query "mutation { issueCreate(input: { teamId: \"$tid\", title: $t, description: $b$p }) { success issue { identifier url } } }" \
    | jq -r '.data.issueCreate.issue | "\(.identifier) \(.url)"'
}

# ---- Stacked-PR merge order --------------------------------------------------

# Walks open PRs from the one based on development upward, so reviewers get an
# explicit bottom-up merge order instead of reverse-engineering the stack.
merge_sequence() {
  gh pr list --state open --json number,title,headRefName,baseRefName 2>/dev/null | jq -r '
    . as $prs
    | def walk($cur):
        if $cur == null then empty
        else "\($cur.number)\t\($cur.headRefName)\t\($cur.title)",
             walk($prs | map(select(.baseRefName == $cur.headRefName)) | first)
        end;
      walk($prs | map(select(.baseRefName == "development")) | first)
  ' | awk -F'\t' '{printf "%d. **#%s** `%s` — %s\n", NR, $1, $2, substr($3,1,60)}'
}

post_merge_sequence() {
  local pr_number="$1" seq
  seq=$(merge_sequence); [ -z "$seq" ] && return 0
  gh pr comment "$pr_number" --body "### Stacked PR — approve and merge in this order

$seq

Merge strictly top-to-bottom. Each PR shows only its own diff, and GitHub
retargets the next one to \`development\` automatically as its parent merges
(head branches are auto-deleted). Merging out of order will conflict.

Per PR: read the CodeRabbit review → check any escalated Linear issues → approve → squash-merge." >/dev/null 2>&1 \
    && log "Posted merge sequence on PR #$pr_number."
}

# ---- Rate limit detection ---------------------------------------------------

extract_reset_epoch() {
  local output="$1" reset_str
  reset_str=$(echo "$output" | grep -ioE "resets? at [0-9:apm ]+" | head -1 | sed -E 's/resets? at //I')
  if [ -n "$reset_str" ]; then
    date -j -f "%I:%M%p" "$(echo "$reset_str" | tr -d ' ' | tr 'a-z' 'A-Z')" "+%s" 2>/dev/null || true
  fi
}

# Only trust the CLI's own error envelope. Grepping the whole transcript for
# "rate limit" false-positives on any issue that is *about* rate limiting — in
# Aegis that threw away two successful runs and slept 5h each time. AssetAuditor
# has AA-16 (LiteLLM rate caps), which would trip exactly that bug.
# A spend cap is NOT a rate limit: no amount of sleeping fixes it, and the run must
# stop dead. On 2026-09-01 this exact case ("You've hit your org's monthly spend
# limit") fell through to the generic failure path and burned 19 queued issues in
# seven minutes — each cut a branch, failed in ~20s, and got pushed to Backlog in
# Linear. One halt is worth more than nineteen false failures.
is_spend_capped() {
  local logfile="$1"
  [ -f "$logfile" ] || return 1
  [ "$(jq -r '.is_error // false' "$logfile" 2>/dev/null)" = "true" ] || return 1
  jq -r '.result // ""' "$logfile" 2>/dev/null \
    | grep -qiE "spend limit|spending limit|insufficient credit|billing limit|raise it at claude\.ai/settings"
}

is_rate_limited() {
  local logfile="$1"
  [ -f "$logfile" ] || return 1
  [ "$(jq -r '.is_error // false' "$logfile" 2>/dev/null)" = "true" ] || return 1
  jq -r '.result // ""' "$logfile" 2>/dev/null \
    | grep -qiE "usage limit|rate limit|reached your.*limit"
}

# ---- Claude invocation -------------------------------------------------------

run_agent() {
  local prompt="$1" logfile="$2" model="$3" tools="${4:-$ALLOWED_TOOLS}"
  local -a model_flag=()
  [ -n "$model" ] && model_flag=(--model "$model")
  # macOS ships bash 3.2, where "${arr[@]}" on an EMPTY array under `set -u` is an
  # unbound-variable fatal — which would kill every run, since no model override is
  # the default. ${arr[@]+"${arr[@]}"} is the 3.2-safe expansion. Do not "simplify".
  claude -p "$prompt" \
    --output-format json \
    --allowedTools "$tools" \
    --permission-mode acceptEdits \
    --max-turns "$MAX_TURNS" \
    ${model_flag[@]+"${model_flag[@]}"} \
    > "$logfile" 2>&1
}

# ---- CodeRabbit gate ---------------------------------------------------------

# `--agent` output shape is not a stable contract, so parse defensively: whole
# JSON, then NDJSON, then plain text. A parse failure must never look like
# "zero findings" — that would let unreviewed code masquerade as clean.
# A review that aborted emits no findings — same shape as a review that found
# nothing. Only a run reaching `complete` may be read as clean. cr_is_rate_limited
# catches one abort cause; this catches all of them (connection drops, crashes).
# Observed 2026-09-02: sweeps of PR #6 and #7 died on "Connection failed" and were
# both recorded as "settled, clean", clearing the debt on unreviewed branches.
# The fix agent is *told* to commit each round as `fix(<ISSUE>): address CodeRabbit
# round N`, and until now nothing checked that it did. On KCH-55 it amended into its
# feature commit instead: the fixes shipped and the branch reviewed clean, but rounds
# 1-3 left no trace, so the PR could not show which commit answered which finding.
# `git add -u` is tracked-only on purpose — an unattended run must never sweep a
# stray scratch file into a reviewed PR (same rule as the pre-push commit).
verify_fix_commit() {
  local identifier="$1" round="$2" pre_count="$3" pre_head="$4"
  local post_count; post_count=$(git rev-list --count HEAD 2>/dev/null || echo 0)
  [ "${post_count:-0}" -gt "${pre_count:-0}" ] && return 0

  git add -u >/dev/null 2>&1
  if ! git diff --cached --quiet; then
    git commit -q -m "fix($identifier): address CodeRabbit round $round"
    log "$identifier: fix round $round left its work uncommitted — committed it here."
    return 0
  fi
  if [ "$(git rev-parse HEAD 2>/dev/null)" != "$pre_head" ]; then
    log "$identifier: WARN — fix round $round amended an existing commit instead of adding one; the finding->fix trail for this round is lost."
  else
    log "$identifier: WARN — fix round $round produced no commit and no changes."
  fi
  return 0
}

cr_completed() {
  [ -s "$1" ] || return 1
  [ "$(grep '^{' "$1" 2>/dev/null | jq -sr 'any(.[]; .type=="complete")' 2>/dev/null)" = "true" ]
}

cr_normalise() {
  local f="$1"
  # `grep '^{'` first: CodeRabbit appends plain-text lines (e.g. "Error: Rate limit
  # exceeded") after its NDJSON, which makes jq fail on the whole file.
  # -s (slurp) ALWAYS: collapses one-or-many JSON documents into exactly one array,
  # so NDJSON does not emit one result per line (that produced "1\n0" and blew up
  # the caller's integer test).
  # The select() must match CodeRabbit's REAL finding shape, observed on KCH-47:
  #   {"type":"finding","severity":"major","fileName":...,"codegenInstructions":...}
  # There is no message/title/description field, so the old filter matched nothing
  # and every count silently fell through to grepping for the word "major".
  grep '^{' "$f" 2>/dev/null | jq -sc '[.[] | .. | objects
          | select(.type == "finding"
                   or ((has("severity") or has("level") or has("priority"))
                       and (has("message") or has("title") or has("description")
                            or has("codegenInstructions"))))]' 2>/dev/null
}

# CodeRabbit's OWN quota, distinct from ours: the free plan includes 8 reviews that
# replenish over minutes. Observed on KCH-47 round 1, where it silently downgraded a
# fully-reviewed-and-fixed branch to "unreviewed". It is recoverable — wait and retry.
cr_is_rate_limited() {
  local f="$1"
  [ -f "$f" ] || return 1
  grep -q '"errorType":"rate_limit"' "$f" 2>/dev/null \
    || grep -qi "rate limit exceeded" "$f" 2>/dev/null
}

cr_blocking_count() {
  local f="$1" norm n
  [ -s "$f" ] || { echo 0; return 0; }
  if norm=$(cr_normalise "$f") && [ -n "$norm" ] && [ "$norm" != "null" ] && [ "$norm" != "[]" ]; then
    n=$(printf '%s' "$norm" | jq --arg re "$CR_BLOCKING" \
      '[.[] | ((.severity // .level // .priority) | tostring | ascii_downcase) | select(test($re))] | length' 2>/dev/null)
    n=$(printf '%s' "${n:-}" | head -1 | tr -dc '0-9')
    [ -n "$n" ] && { echo "$n"; return 0; }
  fi
  # Text fallback: count lines naming a blocking severity. `grep -c` already prints
  # 0 when nothing matches but exits 1, so `|| true` — NOT `|| echo 0`, which would
  # emit a second line and hit the same integer-test bug from the other direction.
  n=$(grep -ciE "(${CR_BLOCKING})" "$f" 2>/dev/null || true)
  n=$(printf '%s' "${n:-0}" | head -1 | tr -dc '0-9')
  echo "${n:-0}"
}

# Sets: CR_STATUS (clean|resolved|escalated|unavailable), CR_SUMMARY, CR_ESCALATED
# The `complete` event carries the authoritative finding count. Severity-based
# counting alone can report "0 blocking" for a review that raised findings whose
# shape we failed to classify — which would print "clean" on a PR that is not.
cr_total_findings() {
  local f="$1" n norm
  n=$(jq -sr '[.[] | select(.type=="complete") | .findings] | last // empty' "$f" 2>/dev/null)
  n=$(printf '%s' "${n:-}" | head -1 | tr -dc '0-9')
  [ -n "$n" ] && { echo "$n"; return 0; }
  norm=$(cr_normalise "$f")
  n=$(printf '%s' "${norm:-[]}" | jq 'length' 2>/dev/null | head -1 | tr -dc '0-9')
  echo "${n:-0}"
}

coderabbit_gate() {
  local identifier="$1" issue_uuid="$2" base_ref="$3" title="$4"
  CR_STATUS="clean"; CR_SUMMARY=""; CR_ESCALATED=""; CR_QUOTA_HIT=0

  if ! command -v coderabbit >/dev/null; then
    CR_STATUS="unavailable"; CR_SUMMARY="CodeRabbit CLI not installed — this branch was NOT machine-reviewed."
    return 0
  fi

  local round=0 findings blocking sleep_guard=0 saw_findings=0
  while [ "$round" -le "$CR_MAX_ROUNDS" ]; do
    findings="$LOG_DIR/${identifier}_coderabbit_r${round}.json"
    local cr_exit=0 rl_wait=0
    while :; do
      log "$identifier: CodeRabbit review (round $round) against $base_ref..."
      # -c CLAUDE.md gives the reviewer the project's standards, so findings land in
      # AssetAuditor's terms (provenance, masking, Decimal, raw-SQL discipline).
      coderabbit review --agent --committed --base "$base_ref" -c CLAUDE.md > "$findings" 2>&1
      cr_exit=$?
      cr_is_rate_limited "$findings" || break
      # Free tier by choice: CodeRabbit's quota is expected to run out, and blocking
      # the build on it would idle the queue for hours. Default CR_RL_MAX_WAITS=0 —
      # do not wait at all, bank the debt and let the hourly sweeper settle it.
      rl_wait=$((rl_wait+1))
      if [ "$rl_wait" -gt "${CR_RL_MAX_WAITS:-0}" ]; then
        log "$identifier: CodeRabbit free-tier quota exhausted. NOT waiting — deferring review to the hourly sweeper."
        CR_QUOTA_HIT=1
        break
      fi
      log "$identifier: CodeRabbit quota exhausted; waiting ${CR_RL_WAIT_SECS:-90}s, retry $rl_wait..."
      sleep "${CR_RL_WAIT_SECS:-90}"
    done

    # A non-zero exit is ambiguous: some review CLIs exit non-zero precisely BECAUSE
    # they found issues. So only call it unavailable when the output also carries
    # nothing parseable — otherwise an auth error printed to stdout would sail
    # through the counter as "0 blocking findings" and a PR would claim it was
    # reviewed clean when it was never reviewed at all.
    if [ "$cr_exit" -ne 0 ]; then
      local shape textsev
      shape=$(cr_normalise "$findings")
      textsev=$(grep -ciE "(${CR_BLOCKING})" "$findings" 2>/dev/null || true)
      if { [ -z "$shape" ] || [ "$shape" = "[]" ]; } && [ "${textsev:-0}" -eq 0 ]; then
        # Quota exhaustion is not a failure — it is expected on the free tier, and
        # the review is deferred rather than skipped. The debt ledger is what makes
        # that a promise instead of a hole.
        if [ "${CR_QUOTA_HIT:-0}" = "1" ]; then
          if [ "$saw_findings" -eq 1 ]; then
            CR_STATUS="deferred_unverified"
            CR_SUMMARY="CodeRabbit reviewed this branch and its blocking findings were fixed, but the confirming re-review hit the free-tier quota. **Queued for the hourly review sweeper** — it will re-review, and any new findings are fixed and reported back here automatically."
          else
            CR_STATUS="deferred"
            CR_SUMMARY="CodeRabbit's free-tier quota was exhausted before this branch could be reviewed. Development did not wait. **Queued for the hourly review sweeper** — it will review, fix what it can, and comment here with anything escalated."
          fi
          return 0
        fi
        if [ "$saw_findings" -eq 1 ]; then
          # An earlier round DID review this branch and its findings were fixed; only
          # the confirmation pass failed. That is a very different thing from
          # "never reviewed", and conflating them sent the owner hunting through a
          # PR that had in fact been reviewed and corrected (KCH-47 / PR #7).
          log "$identifier: earlier rounds reviewed and fixes were applied; verification pass unavailable (exit $cr_exit)."
          CR_STATUS="unverified"
          CR_SUMMARY="CodeRabbit reviewed this branch and its blocking findings were fixed, but the **verification re-review could not run** ($(cr_is_rate_limited "$findings" && echo "CodeRabbit's own review quota was exhausted" || echo "exit $cr_exit")). The fixes are unconfirmed by a second pass — worth a closer look, but this branch was not left unreviewed. Output: \`ops/logs/$(basename "$findings")\`"
        else
          log "$identifier: CodeRabbit failed to run (exit $cr_exit, no parseable findings)."
          CR_STATUS="unavailable"
          CR_SUMMARY="CodeRabbit could not run (exit $cr_exit$(cr_is_rate_limited "$findings" && echo "; its own review quota was exhausted")). This branch was **NOT machine-reviewed** — review it by hand. Output: \`ops/logs/$(basename "$findings")\`"
        fi
        return 0
      fi
      log "$identifier: CodeRabbit exited $cr_exit but produced findings; continuing with the gate."
    fi

    blocking=$(cr_blocking_count "$findings")
    [ "${blocking:-0}" -gt 0 ] && saw_findings=1
    log "$identifier: CodeRabbit round $round — $blocking blocking finding(s)."

    if [ "${blocking:-0}" -eq 0 ]; then
      local total; total=$(cr_total_findings "$findings")
      if [ "${total:-0}" -gt 0 ]; then
        # Findings exist but none classified blocking: real nits, or a severity shape
        # we could not read. Either way this is not "clean" — say so on the PR.
        CR_STATUS="advisory"
        CR_SUMMARY="CodeRabbit reported **$total finding(s)**, none classified as blocking (${CR_BLOCKING//|/, })$([ "$round" -gt 0 ] && echo " after $round fix round(s)"). Read them before approving: \`ops/logs/$(basename "$findings")\`"
      elif ! cr_completed "$findings"; then
        # Zero findings from a run that never finished is not a clean branch.
        log "$identifier: round $round reported no findings but never completed — refusing to call it clean."
        if [ "$saw_findings" -eq 1 ]; then
          CR_STATUS="unverified"
          CR_SUMMARY="CodeRabbit reviewed this branch and its blocking findings were fixed, but the confirming re-review **aborted before completing**, so it reported nothing rather than nothing-to-report. The fixes are unconfirmed. Output: \`ops/logs/$(basename "$findings")\`"
        else
          CR_STATUS="unavailable"
          CR_SUMMARY="CodeRabbit's review **aborted before completing** and therefore reported no findings. This branch was **NOT machine-reviewed** — review it by hand. Output: \`ops/logs/$(basename "$findings")\`"
        fi
      else
        [ "$round" -eq 0 ] && CR_STATUS="clean" || CR_STATUS="resolved"
        CR_SUMMARY="CodeRabbit: reviewed, no findings$([ "$round" -gt 0 ] && echo " after $round fix round(s)")."
      fi
      return 0
    fi

    if [ "$round" -eq "$CR_MAX_ROUNDS" ]; then break; fi
    round=$((round+1))

    log "$identifier: sending findings back to the implementing agent (round $round)."
    comment_on_issue "$issue_uuid" "🐇 CodeRabbit raised $blocking blocking finding(s); agent is reworking (round $round/$CR_MAX_ROUNDS)."
    local fixlog="$LOG_DIR/${identifier}_fix_r${round}.json"
    local pre_count pre_head
    pre_count=$(git rev-list --count HEAD 2>/dev/null || echo 0)
    pre_head=$(git rev-parse HEAD 2>/dev/null || echo "")
    run_agent "CodeRabbit reviewed your implementation of $identifier ($title) and raised blocking findings.

Take this review seriously. Fix the underlying pattern, not the symptom.

Findings:
$(head -c 12000 "$findings")

Rules:
- Do NOT silence a finding by disabling a lint rule, adding an ignore comment, or loosening a type.
- If a finding points at a pattern you used in several places, fix every instance.
- Re-run the tests and the linter afterwards; they must pass.
- Commit with: fix($identifier): address CodeRabbit round $round
- If a specific finding is genuinely wrong, out of scope for $identifier, or would
  violate the repo's own rules in CLAUDE.md, do NOT force a fix. Instead append your
  reasoning for that finding to CR_DISPUTE.md in the repo root (do not commit it).
  A mediator agent will adjudicate it." "$fixlog" "$IMPL_MODEL"

    # A usage limit inside a fix round is not a clean round: the findings are still
    # there and the branch is half-fixed. Sleep and redo this same round rather than
    # letting the loop conclude the code improved.
    if is_rate_limited "$fixlog"; then
      sleep_guard=$((sleep_guard+1))
      if [ "$sleep_guard" -gt 3 ]; then
        log "$identifier: rate-limited 3x inside the CodeRabbit gate — stopping the gate."
        CR_STATUS="escalated"
        CR_SUMMARY="Usage limits repeatedly interrupted the CodeRabbit fix rounds; $blocking blocking finding(s) were left unaddressed. **Review this PR by hand.**"
        return 0
      fi
      local rs; rs=$(extract_reset_epoch "$(cat "$fixlog")")
      local ws=$((5*3600)); [ -n "$rs" ] && ws=$(( rs - $(date +%s) )); [ "$ws" -lt 0 ] && ws=$((5*3600))
      log "$identifier: usage limit during fix round $round — sleeping $((ws/60))m, then redoing this round."
      comment_on_issue "$issue_uuid" "⏸️ Usage limit reached mid-CodeRabbit-rework. Auto-resuming after the window resets."
      sleep "$ws"
      round=$((round-1))
    else
      verify_fix_commit "$identifier" "$round" "$pre_count" "$pre_head"
    fi
  done

  # Blocking findings survived the fix rounds → mediator adjudicates.
  log "$identifier: $blocking blocking finding(s) survived $CR_MAX_ROUNDS rounds — invoking mediator."
  local medlog="$LOG_DIR/${identifier}_mediator.json"
  rm -f "$REPO_DIR/MEDIATION_OUT.json"
  run_agent "You are the mediator for Linear issue $identifier ($title). You are NOT the implementer.

The implementing agent has had $CR_MAX_ROUNDS attempts at CodeRabbit's blocking findings and some remain.

Surviving findings:
$(head -c 12000 "$findings")

The implementer's disputes (may be absent):
$(head -c 6000 "$REPO_DIR/CR_DISPUTE.md" 2>/dev/null || echo '(none written)')

Read the actual code before judging — CodeRabbit can be wrong, and the implementer can be
wrong about CodeRabbit being wrong. Weigh every finding against docs/adr/ADR_v1.1.0.md and
CLAUDE.md (provenance-first, masking before any LLM call, Decimal for money, parameterized
raw SQL only, RLS everywhere, zero-cost contract).

For each surviving blocking finding decide exactly one verdict:
  fixed_now      — small, safe, in scope: make the fix yourself now and commit it
                   (message: fix($identifier): mediator resolves CodeRabbit finding)
  escalate       — legitimate but too large or out of scope for $identifier: it becomes
                   its own Linear issue for the human to triage in the morning
  false_positive — CodeRabbit is wrong: say precisely why
  accepted_risk  — real but deliberately accepted here: say why, and what would change it

Then write /MEDIATION_OUT.json in the repo root (do NOT commit it) with exactly this shape:
{\"verdicts\":[{\"finding\":\"one-line summary\",\"file\":\"path:line\",\"severity\":\"major\",
\"verdict\":\"escalate\",\"rationale\":\"...\",\"issue_title\":\"...\",\"issue_body\":\"...\"}]}
issue_title/issue_body are required only for escalate verdicts; write them as a
self-contained issue an agent could pick up cold (file paths, what good looks like).

Be decisive. Do not escalate something you can safely fix in three lines, and do not
fix something that needs a design decision." "$medlog" "$MEDIATOR_MODEL"

  local med="$REPO_DIR/MEDIATION_OUT.json"
  if [ ! -f "$med" ] || ! jq -e . "$med" >/dev/null 2>&1; then
    log "$identifier: mediator produced no usable verdict file."
    CR_STATUS="escalated"
    CR_SUMMARY="$blocking blocking CodeRabbit finding(s) survived $CR_MAX_ROUNDS rounds and the mediator returned no verdict. **Review this PR by hand.** Findings: \`$(basename "$findings")\`"
    return 0
  fi

  local n_esc=0 esc_lines=""
  while IFS= read -r row; do
    local v t b f
    v=$(jq -r '.verdict' <<<"$row"); f=$(jq -r '.finding' <<<"$row")
    [ "$v" != "escalate" ] && continue
    t=$(jq -r '.issue_title // empty' <<<"$row"); [ -z "$t" ] && t="CodeRabbit follow-up from $identifier: $f"
    b=$(jq -r '.issue_body // empty' <<<"$row")
    b="$b

---
Escalated automatically by the overnight orchestrator from **$identifier**.
CodeRabbit severity: $(jq -r '.severity // "unknown"' <<<"$row") · Location: \`$(jq -r '.file // "unknown"' <<<"$row")\`
Mediator rationale: $(jq -r '.rationale // ""' <<<"$row")"
    local created; created=$(create_linear_issue "$t" "$b" "$issue_uuid")
    if [ -n "$created" ]; then
      n_esc=$((n_esc+1)); esc_lines="$esc_lines
- $created — $f"
      log "$identifier: escalated → $created"
    fi
  done < <(jq -c '.verdicts[]?' "$med")

  local dismissed
  dismissed=$(jq -r '[.verdicts[]? | select(.verdict=="false_positive" or .verdict=="accepted_risk")
                      | "- **\(.verdict)** \(.finding) — \(.rationale)"] | join("\n")' "$med")
  local fixed
  fixed=$(jq -r '[.verdicts[]? | select(.verdict=="fixed_now") | "- \(.finding)"] | join("\n")' "$med")

  CR_ESCALATED="$esc_lines"
  CR_STATUS=$([ "$n_esc" -gt 0 ] && echo "escalated" || echo "resolved")
  CR_SUMMARY="CodeRabbit gate: $blocking blocking finding(s) survived $CR_MAX_ROUNDS agent fix rounds; mediator adjudicated.
$([ -n "$fixed" ] && printf 'Fixed by mediator:\n%s\n' "$fixed")
$([ -n "$esc_lines" ] && printf 'Escalated to Linear (triage in the morning):%s\n' "$esc_lines")
$([ -n "$dismissed" ] && printf 'Dismissed with rationale:\n%s\n' "$dismissed")"
  rm -f "$med" "$REPO_DIR/CR_DISPUTE.md"
  return 0
}

# Best-effort: pull CodeRabbit's SaaS review of the opened PR into Linear, so the
# morning read starts from the same place whether you open Linear or GitHub.
cr_pr_followup() {
  local pr_number="$1" issue_uuid="$2"
  command -v coderabbit >/dev/null || return 0
  local out="$LOG_DIR/pr_${pr_number}_coderabbit.txt"
  # --show-prompts is REQUIRED by this subcommand; --agent alone exits with a usage
  # error (observed on PR #1). Also note CodeRabbit refuses closed PRs, so this is
  # best-effort by design and never gates anything.
  if coderabbit pullrequest "$pr_number" --show-prompts --agent > "$out" 2>&1 && [ -s "$out" ]; then
    comment_on_issue "$issue_uuid" "🐇 CodeRabbit PR review (#$pr_number) excerpt:
\`\`\`
$(head -c 3000 "$out")
\`\`\`"
  fi
}

# ---- Core: run one issue ----------------------------------------------------

run_issue() {
  local identifier="$1"
  log "Fetching $identifier from Linear..."
  local issue_json title description issue_uuid
  issue_json=$(resolve_issue "$identifier")
  issue_uuid=$(jq -r '.id // empty' <<<"$issue_json")
  title=$(jq -r '.title // empty' <<<"$issue_json")
  description=$(jq -r '.description // ""' <<<"$issue_json")

  if [ -z "$issue_uuid" ]; then
    log "ERROR: could not resolve $identifier in Linear, skipping"
    return 2
  fi

  local branch="feature/$(echo "$identifier" | tr '[:upper:]' '[:lower:]')"

  cd "$REPO_DIR" || { log "ERROR: REPO_DIR not found"; return 2; }

  # Own the worktree for this whole issue — the hourly sweeper shares it.
  if ! acquire_worktree 1800; then
    log "$identifier: could not acquire the worktree lock (sweeper busy?) — retrying next pass."
    return 2
  fi

  # Agents routinely leave uncommitted edits behind. Without wiping them the
  # checkout below fails, and since we don't run with `set -e` the script would
  # carry on and cut this issue's branch off the *previous* issue's branch.
  # `clean -fd` (no -x) leaves .gitignore'd orchestrator state alone — but ONLY per
  # the .gitignore of the branch just checked out. Feature branches cut before the
  # lock entries were added carry an older .gitignore, so the locks are untracked
  # there and get deleted mid-run (observed 2026-09-01: .builder.lock vanished under
  # a live build). -e does not depend on the branch, so exclude them explicitly.
  git reset --hard -q
  git clean -fd -q -e .worktree.lock -e .builder.lock -e .sweeper.lock

  # Stacked-PR base selection: if the previous issue's branch exists and is not
  # yet merged into development, cut from it so this agent can build on that
  # (unmerged) work and the PR diff stays incremental.
  git fetch origin --prune --quiet
  local base_branch="development" base_ref="origin/development"
  if [ -n "${LAST_BRANCH:-}" ] && git rev-parse --verify "origin/$LAST_BRANCH" >/dev/null 2>&1; then
    if git merge-base --is-ancestor "origin/$LAST_BRANCH" origin/development 2>/dev/null; then
      log "$identifier: dependency $LAST_BRANCH already merged into development; basing on development."
    else
      base_branch="$LAST_BRANCH"; base_ref="origin/$LAST_BRANCH"
      log "$identifier: stacking on unmerged dependency $LAST_BRANCH."
    fi
  fi

  if ! git checkout -B "$branch" "$base_ref" --quiet; then
    log "ERROR: could not cut $branch from $base_ref. Skipping $identifier."
    release_worktree; return 2
  fi
  local on_branch; on_branch=$(git rev-parse --abbrev-ref HEAD)
  if [ "$on_branch" != "$branch" ]; then
    log "ERROR: expected HEAD on $branch but it is $on_branch. Skipping $identifier."
    release_worktree; return 2
  fi

  set_issue_state "$issue_uuid" "In Progress"
  comment_on_issue "$issue_uuid" "🤖 Overnight agent starting on branch \`$branch\` (base \`$base_branch\`)."

  local contracts=""
  if [ -s "$CONTRACTS_FILE" ]; then
    contracts="
## Contracts from upstream agents (already on this branch)

Committed on the branch you are on but still awaiting human review. Treat these as
settled interfaces: import and build on them, do not reimplement or refactor them.

$(cat "$CONTRACTS_FILE")
"
  fi

  local pg_note="PostgreSQL is NOT available locally; write DB code and tests but say plainly in your summary what could not be executed."
  if pg_isready -q 2>/dev/null || pg_isready -q -h localhost -p 5432 2>/dev/null; then
    pg_note="PostgreSQL 16 is reachable on localhost:5432 (superuser '$(whoami)'${PGHOST:+, TCP — PGHOST is already exported for you}); create your own scratch database. Prefer a real integration test over mocking for DB behaviour."
  fi

  local prompt="You are implementing Linear issue $identifier: $title

Description:
$description
$contracts
## How to work

Read CLAUDE.md first — it is binding. The planning artifacts in this repo are the
source of truth: docs/adr/ADR_v1.1.0.md is the architecture of record, mvp.md holds
the issue specs and dependency spine, data/samples/README.md holds the golden numbers
that tests must reproduce, and skills/e2e-testing/SKILL.md defines acceptance flows.

Implement this issue fully within the existing repo conventions. Write tests. Run the
test suite and the linter before you finish. Do not touch files outside the scope of
this issue. Commit your work with a conventional-commit message referencing $identifier.
Do NOT push and do NOT open a pull request — the orchestrator does that after a
CodeRabbit review gate.

## Environment

$pg_note
Docker: $(docker info >/dev/null 2>&1 && echo 'daemon running' || echo 'installed but NOT running — do not depend on containers').
Available: pytest, ruff, mypy, python3, uv, pip, npm/npx/node ($(node -v 2>/dev/null)), psql,
createdb/dropdb, pip-audit, gitleaks, trivy, git, gh, jq, docker.
You do NOT have curl and there are no cloud credentials on this machine: no Supabase
project, no Vercel token, no Groq key, no GPU box. For anything needing them, write the
code, config, migrations and runbook, prove what you can locally, and state plainly in
your summary what is unverified. Never fake a passing test and never invent a credential.
To exercise HTTP routes use FastAPI's TestClient or httpx inside pytest.

## Definition of done

Tests pass, linter clean, work committed on this branch, and a contract block appended
to CONTRACT_OUT.md in the repo root (do NOT commit that file): module paths, key
classes/functions with signatures, new DB tables or columns. Under 20 lines. Downstream
agents build against it.

Your work will be reviewed by CodeRabbit before a PR is opened. Write it to survive that."

  local logfile="$LOG_DIR/${identifier}_$(date +%s).json"
  log "Running implementing agent for $identifier (branch $branch)..."
  run_agent "$prompt" "$logfile" "$IMPL_MODEL"
  local exit_code=$?
  local output; output=$(cat "$logfile")

  # Check the spend cap FIRST: it is terminal, whereas a rate limit is just a wait.
  if is_spend_capped "$logfile"; then
    log "*** SPEND CAP REACHED on $identifier — halting the run. ***"
    log "*** $(jq -r '.result // ""' "$logfile" 2>/dev/null | head -1) ***"
    comment_on_issue "$issue_uuid" "⛔ Run halted: the account's spend limit was reached before this issue could be implemented. No work was done; the issue is untouched and will be retried on the next run."
    set_issue_state "$issue_uuid" "Backlog"
    report "- ⛔ **$identifier** — run HALTED here: spend limit reached. This issue and everything after it are untouched and will retry."
    release_worktree; return 3
  fi

  if is_rate_limited "$logfile"; then
    log "Hit usage limit while working on $identifier."
    local resume_epoch; resume_epoch=$(extract_reset_epoch "$output")
    local wait_secs=$((5*3600))
    if [ -n "$resume_epoch" ]; then
      wait_secs=$(( resume_epoch - $(date +%s) )); [ "$wait_secs" -lt 0 ] && wait_secs=$((5*3600))
    fi
    log "Sleeping $((wait_secs/60)) minutes until the window resets..."
    comment_on_issue "$issue_uuid" "⏸️ Agent paused: usage limit reached. Auto-resuming this issue after the window resets."
    sleep "$wait_secs"
    release_worktree
    return 1  # caller retries this same issue
  fi

  if [ "$exit_code" -ne 0 ]; then
    log "$identifier failed (exit $exit_code). Log: $logfile"
    comment_on_issue "$issue_uuid" "⚠️ Overnight agent run failed (exit $exit_code). Needs a human. Log excerpt:
\`\`\`
$(echo "$output" | tail -30)
\`\`\`"
    set_issue_state "$issue_uuid" "Backlog"
    report "- ❌ **$identifier** — agent failed (exit $exit_code). Log: \`ops/logs/$(basename "$logfile")\`"
    release_worktree; return 2
  fi

  # Agents sometimes create a branch of their own and commit there. Pushing
  # "$branch" in that case ships whatever it inherited, not the work.
  local head_after; head_after=$(git rev-parse --abbrev-ref HEAD)
  if [ "$head_after" != "$branch" ]; then
    log "$identifier: agent left HEAD on '$head_after', not '$branch'. Not pushing."
    comment_on_issue "$issue_uuid" "⚠️ Agent committed on \`$head_after\` instead of \`$branch\`. Work is local only; no PR opened."
    set_issue_state "$issue_uuid" "Backlog"
    report "- ❌ **$identifier** — agent committed on the wrong branch (\`$head_after\`). Nothing pushed."
    release_worktree; return 2
  fi

  if ! git log "$base_ref".."$branch" --oneline | grep -q .; then
    log "$identifier produced no commits — treating as incomplete."
    set_issue_state "$issue_uuid" "Backlog"
    comment_on_issue "$issue_uuid" "⚠️ Agent run completed but produced no commits. Needs a human look."
    report "- ❌ **$identifier** — no commits produced."
    release_worktree; return 2
  fi

  # ---- CodeRabbit gate before anything is pushed ----
  coderabbit_gate "$identifier" "$issue_uuid" "$base_ref" "$title"
  log "$identifier: CodeRabbit gate status = $CR_STATUS"

  if [ "$CR_STATUS" = "unavailable" ] && [ "$CR_REQUIRED" = "1" ]; then
    log "$identifier: CR_REQUIRED=1 and CodeRabbit unavailable — refusing to push."
    comment_on_issue "$issue_uuid" "⛔ Held back: CodeRabbit could not review this branch and CR_REQUIRED=1. Work is committed locally on \`$branch\`."
    set_issue_state "$issue_uuid" "Backlog"
    report "- ⛔ **$identifier** — held: CodeRabbit unavailable, nothing pushed."
    release_worktree; return 2
  fi

  # The mediator commits its own fixes, but may leave an edit unstaged. `add -u`
  # (tracked files only) rather than `add -A`: an unattended run must never sweep
  # a stray scratch file the agent forgot into a reviewed PR.
  git add -u >/dev/null 2>&1
  git diff --cached --quiet || git commit -q -m "fix($identifier): mediator adjustments from CodeRabbit gate"
  local stray; stray=$(git ls-files --others --exclude-standard | head -5)
  [ -n "$stray" ] && log "$identifier: note — untracked files left behind, NOT committed: $(echo "$stray" | tr '\n' ' ')"

  git push -u origin "$branch" --quiet
  local stack_note=""
  [ "$base_branch" != "development" ] && stack_note="

> **Stacked PR.** Based on \`$base_branch\` ($LAST_ISSUE), still awaiting review.
> GitHub retargets this to \`development\` automatically once the parent merges.
> Review the parent first."

  local cr_badge
  case "$CR_STATUS" in
    clean)       cr_badge="✅ CodeRabbit: clean on first review." ;;
    resolved)    cr_badge="✅ CodeRabbit: blocking findings resolved before this PR opened." ;;
    advisory)    cr_badge="📝 CodeRabbit: non-blocking findings recorded — read before approving." ;;
    unverified)  cr_badge="🔁 CodeRabbit reviewed and its findings were fixed, but the verification re-review could not run." ;;
    deferred)    cr_badge="⏳ CodeRabbit's free-tier quota was exhausted — review DEFERRED to the hourly sweeper, not skipped." ;;
    deferred_unverified) cr_badge="⏳ Reviewed and fixed once; the confirming re-review is DEFERRED to the hourly sweeper." ;;
    escalated)   cr_badge="⚠️ CodeRabbit: findings escalated to Linear — read before approving." ;;
    unavailable) cr_badge="⛔ CodeRabbit did NOT review this branch. Treat as unreviewed." ;;
  esac

  local pr_url
  pr_url=$(gh pr create --title "$identifier: $title" \
    --body "Automated implementation of $identifier by the overnight orchestrator. **Human review required — this will not auto-merge.**$stack_note

### CodeRabbit gate
$cr_badge

$CR_SUMMARY

### Review order
See the stacked-merge comment below. Approve and squash-merge bottom-up.

_Spec: \`mvp.md\` ($identifier) · Architecture: \`docs/adr/ADR_v1.1.0.md\`_" \
    --base "$base_branch" --head "$branch" 2>&1 | tail -1)

  local pr_number; pr_number=$(basename "$pr_url")
  # Bank any unfinished review now that the PR exists, so the sweeper can find it.
  case "$CR_STATUS" in
    deferred)            record_review_debt "$pr_number" "$branch" "$identifier" "never_reviewed" ;;
    deferred_unverified) record_review_debt "$pr_number" "$branch" "$identifier" "unverified" ;;
    unavailable)         record_review_debt "$pr_number" "$branch" "$identifier" "never_reviewed" ;;
    unverified)          record_review_debt "$pr_number" "$branch" "$identifier" "unverified" ;;
  esac
  post_merge_sequence "$pr_number"
  cr_pr_followup "$pr_number" "$issue_uuid"
  # Publish the gate's evidence and set a real commit status. The badge in the body
  # above is an assertion; ops/logs is gitignored, so without this GitHub has no way
  # to show what was found or that it was answered — and nothing to block a merge on.
  if "$OPS_DIR/pr_gate.sh" --pr "$pr_number" --apply >>"$LOG_DIR/pr_gate.log" 2>&1; then
    log "$identifier: PR #$pr_number gate evidence published."
  else
    log "$identifier: WARN — gate evidence FAILED for PR #$pr_number; see ops/logs/pr_gate.log"
  fi


  comment_on_issue "$issue_uuid" "✅ Agent finished. PR: $pr_url (base \`$base_branch\`) — awaiting human review, will NOT auto-merge.

$CR_SUMMARY"
  set_issue_state "$issue_uuid" "In Review"
  echo "$identifier" >> "$STATE_FILE"
  log "$identifier done -> $pr_url"

  local rep_icon="✅"; [ "$CR_STATUS" = "advisory" ] && rep_icon="📝"; [ "$CR_STATUS" = "unverified" ] && rep_icon="🔁"; case "$CR_STATUS" in deferred|deferred_unverified) rep_icon="⏳";; esac; [ "$CR_STATUS" = "escalated" ] && rep_icon="⚠️"; [ "$CR_STATUS" = "unavailable" ] && rep_icon="⛔"
  report "- $rep_icon **$identifier** $title — $pr_url (base \`$base_branch\`) · CodeRabbit: $CR_STATUS$CR_ESCALATED"

  if [ -f "$REPO_DIR/CONTRACT_OUT.md" ]; then
    { echo ""; echo "### $identifier — $title"; echo "_Branch \`$branch\`, PR $pr_url, awaiting merge._"; echo ""
      cat "$REPO_DIR/CONTRACT_OUT.md"; } >> "$CONTRACTS_FILE"
    rm -f "$REPO_DIR/CONTRACT_OUT.md"
    log "$identifier: contract recorded for downstream agents."
  else
    log "$identifier: WARNING — no CONTRACT_OUT.md; downstream agents get no interface summary."
  fi

  LAST_BRANCH="$branch"; LAST_ISSUE="$identifier"
  release_worktree
  return 0
}

# ---- Main loop ---------------------------------------------------------------

# Sourced as a library by ops/remediate_prs.sh, which reuses the Linear helpers,
# the CodeRabbit parsers, run_agent and merge_sequence rather than duplicating
# them. Returns when sourced; exits cleanly if someone runs it with the flag set.
if [ "${ORCHESTRATOR_LIB_ONLY:-0}" = "1" ]; then
  return 0 2>/dev/null || exit 0
fi

preflight

report ""
report "# Night report — $(date '+%Y-%m-%d %H:%M')"
report ""
log "Starting AssetAuditor orchestrator. Repo: $REPO_DIR · Team: $LINEAR_TEAM_KEY"

while IFS=$'\t' read -r tier identifier parallel; do
  [[ "$tier" =~ ^#.*$ || -z "${tier:-}" ]] && continue
  grep -qx "$identifier" "$STATE_FILE" && { log "Skipping $identifier (already done)"; continue; }

  # Tier 4 holds the kill gate: deterministic PDF parsing. If a text-layer bank
  # statement cannot be parsed into the same rows as its CSV fixture, the whole
  # "upload your statements" premise is unproven and the tiers above it are waste.
  if [ "$tier" = "4" ] && [ "${KILL_GATE_ISSUE:-}" = "$identifier" ]; then
    log "*** KILL GATE ($identifier): statement parsing must reproduce the fixture rows. ***"
  fi

  attempts=0; failed=0
  until run_issue "$identifier"; do
    rc=$?
    attempts=$((attempts+1))
    if [ "$rc" -eq 3 ]; then
      # Terminal account-level stop. Everything still queued is untouched and will
      # be picked up verbatim on the next run — do not march through it failing.
      log "Stopping the queue: spend limit reached. Remaining issues are untouched."
      report ""
      report "Run halted at $identifier — spend limit reached. $(grep -c . "$STATE_FILE") issue(s) completed in total; the rest will retry on the next run."
      merge_sequence >> "$REPORT_FILE" 2>/dev/null
      exit 2
    fi
    if [ "$rc" -eq 2 ]; then
      log "$identifier needs a human, moving on (not retrying automatically)."
      failed=1; break
    fi
    if [ "$attempts" -ge 3 ]; then
      log "$identifier: rate-limited 3x in a row — stopping for a human check."
      report ""; report "Loop stopped early: $identifier rate-limited three times."
      exit 1
    fi
    # rc == 1: rate limit, already slept inside run_issue; retry same issue
  done

  if [ "${KILL_GATE_ISSUE:-}" = "$identifier" ] && [ "$failed" -eq 1 ]; then
    log "*** KILL GATE FAILED ($identifier). Stopping before later tiers spend more budget."
    log "*** Reassess parsing feasibility, then re-run. Set SKIP_KILL_GATE=1 to override. ***"
    report ""; report "**KILL GATE FAILED at $identifier** — deterministic statement parsing is unproven. Later tiers were not attempted."
    [ "${SKIP_KILL_GATE:-0}" = "1" ] || exit 1
  fi
done < "$QUEUE_FILE"

report ""
report "## Merge order for this morning"
report ""
merge_sequence >> "$REPORT_FILE" 2>/dev/null || report "_(no open PRs)_"
report ""
report "Approve and squash-merge bottom-up. For each PR: read the CodeRabbit review → check escalated Linear issues → approve → merge. GitHub retargets the child PR automatically and deletes the head branch."

log "Queue exhausted. Night report: $REPORT_FILE"
