#!/usr/bin/env bash
# ops/pr_gate.sh — publish the CLI gate's evidence onto the PR and set a real check.
#
# Why this exists. The CodeRabbit CLI gate runs PRE-PUSH, so by the time a PR is
# opened its fix commits are already baked into the first commit set — there is no
# "found X, then fixed X" timeline for a reviewer to follow. The findings themselves
# live in ops/logs/*_coderabbit_r*.json, which is gitignored and never leaves this
# Mac. All GitHub ever saw was a one-line badge in the PR body: an assertion nobody
# could verify, and no status check to gate a merge on.
#
# This script closes that. Per PR it republishes, from the local round files:
#   * every finding CodeRabbit raised, per round, with severity and file
#   * the commit that answered each round
#   * the final re-review result
# then sets a `coderabbit/cli-gate` commit status on the PR head so the gate is a
# check, not prose. Make it a required status in branch protection and an unreviewed
# branch cannot be merged.
#
# No Claude involved: bash, gh and the logs only. Safe while the spend limit is hit.
#
#   ./ops/pr_gate.sh                    # dry run over every open PR
#   ./ops/pr_gate.sh --apply            # post comments and set statuses
#   ./ops/pr_gate.sh --pr 14 --apply    # one PR
#   ./ops/pr_gate.sh --render KCH-50 --branch origin/feature/kch-50   # no network

set -uo pipefail

OPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# orchestrator.sh re-execs from a copy in $TMPDIR and calls "$OPS_DIR/pr_gate.sh", so
# OPS_DIR may be that copy. It exports REPO_DIR and AA_REAL_OPS for exactly this —
# deriving either from OPS_DIR lands in $TMPDIR, where there is no git repo and no logs.
REPO_DIR="${REPO_DIR:-$(cd "${AA_REAL_OPS:-$OPS_DIR}/.." && pwd)}"
LOG_DIR="${AA_REAL_OPS:-$OPS_DIR}/logs"
CR_BLOCKING="${CR_BLOCKING:-critical|major|blocker|high}"
MARKER="<!-- aa-cli-gate -->"

APPLY=0; ONLY_PR=""; RENDER=""; RENDER_BRANCH=""
while [ $# -gt 0 ]; do
  case "$1" in
    --apply)  APPLY=1 ;;
    --pr)     ONLY_PR="${2:-}"; shift ;;
    --render) RENDER="${2:-}"; shift ;;
    --branch) RENDER_BRANCH="${2:-}"; shift ;;
    -h|--help) sed -n '2,28p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

# CodeRabbit emits NDJSON with plain-text lines appended, so grep '^{' before jq and
# slurp: a parse failure must never be indistinguishable from "no findings".
findings_of() { grep '^{' "$1" 2>/dev/null | jq -sr '.[]|select(.type=="finding")' 2>/dev/null; }
count_of()    { findings_of "$1" | jq -sr 'length' 2>/dev/null || echo "ERR"; }
blocking_of() { findings_of "$1" | jq -sr --arg re "$CR_BLOCKING" '[.[]|select(.severity|test($re))]|length' 2>/dev/null || echo "ERR"; }

# Build the comment body for one issue. Echoes the body; sets GATE_STATE/GATE_DESC.
render_issue() {
  local issue="$1" branch="${2:-}"
  local rounds=("$LOG_DIR"/${issue}_coderabbit_r*.json)
  local body="$MARKER
### CodeRabbit CLI gate — evidence

The CLI gate runs before the branch is pushed, so these fixes are already part of this
PR's first commit set. This is the trail GitHub could not otherwise see."

  if [ ! -e "${rounds[0]}" ]; then
    GATE_STATE="failure"; GATE_DESC="Never machine-reviewed — no CLI gate ran"
    echo "$body

> ⛔ **No CLI review exists for \`$issue\`.** No round files under \`ops/logs/\`. This
> branch was never machine-reviewed — treat it as unreviewed and read it by hand.

_Generated by \`ops/pr_gate.sh\` from local gate logs._"
    return
  fi

  local last_block=0 last_round=-1 total_fixed=0 table=""
  for f in "${rounds[@]}"; do
    local r n b fixc
    r=$(basename "$f" | sed 's/.*_r\([0-9]*\)\.json/\1/')
    n=$(count_of "$f"); b=$(blocking_of "$f")
    [ "$n" = "ERR" ] && { n="?"; b="?"; }
    # the commit that answered THIS round is the one the next round re-reviewed
    fixc=$(cd "$REPO_DIR" && git log --format='%h' ${branch:+"$branch"} \
             --grep="fix($issue): address CodeRabbit round $((r+1))" 2>/dev/null | head -1)
    [ -n "$fixc" ] && total_fixed=$((total_fixed+1))
    table="$table
| round $r | $n | $b | ${fixc:-—} |"
    last_block="$b"; last_round="$r"
  done

  body="$body

| Review | Findings | Blocking | Answered by |
|---|---|---|---|$table

**Blocking severities:** \`${CR_BLOCKING//|/\`, \`}\`
"

  # Per-round finding detail — what was actually said.
  for f in "${rounds[@]}"; do
    local r; r=$(basename "$f" | sed 's/.*_r\([0-9]*\)\.json/\1/')
    local det; det=$(findings_of "$f" | jq -sr '.[]|"- **\(.severity)** `\(.fileName)`"' 2>/dev/null)
    [ -n "$det" ] && body="$body
<details><summary>Round $r findings</summary>

$det
</details>
"
  done

  if [ "$last_block" = "0" ]; then
    GATE_STATE="success"
    GATE_DESC="Reviewed; blocking findings resolved (round $last_round clean)"
    body="$body
✅ **Final re-review (round $last_round) returned no blocking findings.** Every blocking
finding raised was answered by a commit in this PR and confirmed clean by a fresh review."
  else
    GATE_STATE="failure"
    GATE_DESC="$last_block blocking finding(s) unresolved at round $last_round"
    body="$body
⚠️ **$last_block blocking finding(s) still open at round $last_round.** Do not approve on the
strength of this gate — read the findings above."
  fi
  echo "$body

_Generated by \`ops/pr_gate.sh\` from local gate logs._"
}

# ---- render-only mode: no network, prove the output ---------------------------
if [ -n "$RENDER" ]; then
  render_issue "$RENDER" "$RENDER_BRANCH"
  echo; echo "---- status would be: $GATE_STATE — $GATE_DESC" >&2
  exit 0
fi

command -v gh >/dev/null || { echo "FATAL: gh not installed."; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "FATAL: gh not authenticated (gh auth login)."; exit 1; }
NWO=$(gh repo view --json nameWithOwner -q .nameWithOwner) || exit 1

rc=0
prs=$(gh pr list --state open --json number -q '.[].number')
[ -n "$ONLY_PR" ] && prs="$ONLY_PR"
[ -z "$prs" ] && { echo "No open PRs."; exit 0; }

for pr in $prs; do
  read -r branch sha <<<"$(gh pr view "$pr" --json headRefName,headRefOid \
                            -q '"\(.headRefName) \(.headRefOid)"' 2>/dev/null)"
  [ -z "${branch:-}" ] && { echo "PR #$pr: could not read head — skipped."; continue; }
  issue=$(echo "$branch" | sed 's|^feature/||' | tr '[:lower:]' '[:upper:]')

  GATE_STATE=""; GATE_DESC=""
  body=$(render_issue "$issue" "origin/$branch")

  if [ "$APPLY" -eq 0 ]; then
    echo "=== PR #$pr ($branch → $issue) — would set: $GATE_STATE — $GATE_DESC"
    continue
  fi

  # One comment per PR: update in place rather than stacking a new one each run.
  existing=$(gh api "repos/$NWO/issues/$pr/comments" --paginate \
               -q ".[]|select(.body|startswith(\"$MARKER\"))|.id" 2>/dev/null | head -1)
  if [ -n "$existing" ]; then
    gh api -X PATCH "repos/$NWO/issues/comments/$existing" -f body="$body" >/dev/null \
      && echo "PR #$pr: comment updated"
  else
    gh api -X POST "repos/$NWO/issues/$pr/comments" -f body="$body" >/dev/null \
      && echo "PR #$pr: comment posted"
  fi

  if err=$(gh api -X POST "repos/$NWO/statuses/$sha" \
             -f state="$GATE_STATE" -f context="coderabbit/cli-gate" \
             -f description="$(echo "$GATE_DESC" | cut -c1-138)" 2>&1 >/dev/null); then
    echo "PR #$pr: status $GATE_STATE — $GATE_DESC"
  else
    # Setting a commit status needs a token with repo:status. Say so rather than
    # failing mutely — this is the step that makes the gate a gate.
    echo "PR #$pr: FAILED to set status — $(echo "$err" | head -2 | tr '\n' ' ')" >&2
    rc=1
  fi
done
exit $rc
